### ISSUE TITLE
how can i get all followers name

### ISSUE THREAD

**Issue by myselfgaurav** [J7mbo/twitter-api-php#100]
i want to get all follower name how can i get pls help

**Comment by teklifeinfo** [comment]
You can get up to 200 names per page using

https://dev.twitter.com/rest/reference/get/followers/list

**Comment by myselfgaurav** [comment]
what if more that 200 follower say 600 follower how can i get it

**Comment by teklifeinfo** [comment]
put it in a loop, and process 200 at a time

http://stackoverflow.com/questions/28211116/fetch-all-twitter-followers-using-php-api-with-cursors

that might help
