### ISSUE TITLE
could not get user all tweets 

### ISSUE THREAD

**Issue by myselfgaurav** [J7mbo/twitter-api-php#102]
i am using below code :

$settings = array(
    'oauth_access_token' => "",
    'oauth_access_token_secret' => "",
    'consumer_key' => "",
    'consumer_secret' => ""
);
$requestMethod = 'GET';
$url1="https://api.twitter.com/1.1/statuses/user_timeline.json";

$sc_name = 'DailyRapPics';
$count ='3200';

	$getfield = '?screen_name='.$sc_name.'&exclude_replies=false&include_rts=true&contributor_details=true&count='.$count;

$twitter = new TwitterAPIExchange($settings);
$tweets  = $twitter->setGetfield($getfield)->buildOauth($url1, $requestMethod)->performRequest();

echo '<pre>';
$tweetarray = json_decode($tweets);
print_r($tweetarray);
echo '</pre>';

but it return only 200 tweets but this user have 470 tweets what am i missing

**Comment by J7mbo** [comment]
The [documentation](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) states:

> **count (optional)**: Specifies the number of tweets to try and retrieve, up to a maximum of 200 per distinct request.

**Comment by myselfgaurav** [comment]
yeah i want to get tweets more that 200 say 400 can you please do it form me i will pay you $5 please help i need it

**Comment by myselfgaurav** [comment]
hey please tell how can i get since_id and max_id

**Comment by stephenwf** [comment]
Grab 200, get the timestamp of the last one and make a second (or as many as you need) passing the last timestamp to since_id.

You could make a wrapper to just loop until the whole timeline is loaded. If you are doing this, make sure to not make the request too often, cache and get "updates" to the timeline using since_id of the last tweet you cached.

Hope that helps.
