### ISSUE TITLE
Just returning null after a search tweets json request

### ISSUE THREAD

**Issue by KingZing** [J7mbo/twitter-api-php#106]
Hi guys,

This is my code:

<?php
require_once('../twitter-api-php-master/TwitterAPIExchange.php');

$settings = array(
  'oauth_access_token' => "MYVALUE",
  'oauth_access_token_secret' => "MYVALUE",
  'consumer_key' => "MYVALUE",
  'consumer_secret' => "MYVALUE"
);

$url = 'https://api.twitter.com/1.1/search/tweets.json';
$getfield = '?q=esports';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);

$response = $twitter->setGetfield($getfield)->buildOauth($url, $requestMethod)->performRequest();

var_dump(json_decode($response));
?>

For some reason I am getting null back? Is there anything I'm doing wrong? 

I have tried it with the '#' and the %23 but still no joy, and just returning null, it has been so hard just to try and get this to work, am I missing anything?

EDIT:

Adding: CURLOPT_SSL_VERIFYPEER => false in performRequest() method solved the issue, maybe this needs updating in the php file itself?

**Comment by iMezied** [comment]
the same issue 
and @KingZing fix solving this 
thank you

**Comment by purdy** [comment]
I was having a similar issue and instead of disabling the SSL verification, I changed the SSL path, which fixed my issue and ensured security.

    CURLOPT_CAINFO => '/etc/ssl/certs/cacert.org.pem',
