### ISSUE TITLE
Could not authenticate error in the latest version

### ISSUE THREAD

**Issue by gitboss** [J7mbo/twitter-api-php#111]
The following simple code works with the older version 

	$url = 'https://api.twitter.com/1.1/search/tweets.json';
	$getfield = '?q=' . urlencode($query) . "&rpp=100" . ($max_id ? "&since_id=" . $max_id : "") ;
	$requestMethod = 'GET';
	$twitter = new TwitterAPIExchange($settings);
	$response = $twitter->setGetfield($getfield)
						->buildOauth($url, $requestMethod)
						->performRequest();
	return $response;

However I get "Could not authenticate error" while using the latest version of the wrapper which was updated yesterday. BTW - media uploads works with the latest version.

**Comment by J7mbo** [comment]
Could you change your `$getField` query to a very simple query, without the `urlencode()`, and let me know the result?

**Comment by gitboss** [comment]
I changed $getfield to '?q=james' and it worked with the latest version. I'm trying to search for URLs within the tweets e.g. '?q=http%3A%2F%2Fwwww.google.com'. The latest version returns "Could not authenticate" error while searching for URLs.

**Comment by J7mbo** [comment]
Have you tried `?q=http://www.google.com`?

**Comment by gitboss** [comment]
Yes, I tried ?q=http://www.google.com and it returned the same error with the latest version. Works with older version. I even replaced &rpp with &count as per the latest documentation on Twitter.com. The latest version I think has issues searching for URLs.

**Comment by J7mbo** [comment]
Ok, I've nailed it down to it not supporting `:` and `/` characters properly (`httpwww.google.com` works). I'll update once I've found a fix.

**Comment by J7mbo** [comment]
@gitboss For the moment, you can ignore http:// and just use: `?q=google.com` or `?q=www.google.com`, that'll nail you more hits than requiring the http as well.

**Comment by digfish** [comment]
Hum, I was using a "#" (without the quotes) in the query string (?q=#eleicoes). I removed the "#" and then imediatelly suceeded !

**Comment by whatadewitt** [comment]
Getting a similar issue with the following...

```
require_once('lib/TwitterAPIExchange.php');

    $settings = array(
      'oauth_access_token' => self::TWITTER_OAUTH_KEY,
      'oauth_access_token_secret' => self::TWITTER_OAUTH_SECRET,
      'consumer_key' => self::TWITTER_CONSUMER_KEY,
      'consumer_secret' => self::TWITTER_OAUTH_SECRET
    );

    $url = 'https://api.twitter.com/1.1/statuses/user_timeline.json';
    $getfield = '?screen_name=' . self::USERNAME;
    $requestMethod = 'GET';

    $twitter = new TwitterAPIExchange($settings);
    $resp = $twitter->setGetfield($getfield)
                 ->buildOauth($url, $requestMethod)
                 ->performRequest();
```

Any ideas?

--d

**Comment by glenscott** [comment]
@whatadewitt are you using the latest version of TwitterAPIExchange.php?  I've tested your query using the version on dev-master and it works fine.

**Comment by whatadewitt** [comment]
My damned keyboard didn't copy my variable properly. Was my own mistake. Sorry!

**Comment by J7mbo** [comment]
I added a test to disprove that for the future, so it's a good thing you mentioned it anyway. +1 extra test :-)

**Comment by J7mbo** [comment]
@gitboss Could you confirm that this works for you in the latest version (`1.0.1`)?

**Comment by femiadeyemi** [comment]
@J7mbo I just tested it now and it's working fine. 
@gitboss by the way, with the latest version of this library, you don't need to encode the url.
I think this issue should be close. Thanks!

**Comment by J7mbo** [comment]
Thanks for helping debug / fix on this one guys :+1:
