### ISSUE TITLE
Could not authenticate you

### ISSUE THREAD

**Issue by MarwanMR1** [J7mbo/twitter-api-php#113]
Hi,
I keep getting the following JSON whenever I try to use search.
```
object(stdClass)#2 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#3 (2) { ["code"]=> int(32) ["message"]=> string(27) "Could not authenticate you." } } }
```
I copied the code for "Search global tweets for a hashtag" from "Basic Examples" and I keep getting that error. When I try the "Get a user's tweets" example, it works and returns data. The following is the whole php file I'm using. I replaced the actual keys and secret keys with Xs.
```php
<?php
require_once('TwitterAPIExchange.php');

$settings = array(
    'oauth_access_token' => "XXXXXX",
    'oauth_access_token_secret' => "XXXXXX",
    'consumer_key' => "XXXXXX",
    'consumer_secret' => "XXXXXX"
);

$url = 'https://api.twitter.com/1.1/search/tweets.json';
$getfield = '?q=#nerd';
$requestMethod = 'GET';

$twitter = new TwitterAPIExchange($settings);
$response = $twitter->setGetfield($getfield)
    ->buildOauth($url, $requestMethod)
    ->performRequest();

var_dump(json_decode($response));
?>
```

**Comment by glenscott** [comment]
Fixed in this pull request: https://github.com/J7mbo/twitter-api-php/pull/112

**Comment by J7mbo** [comment]
@MarwanMR1 The above version `1.0.1` should have fixed this. Could you let us know if it works.

**Comment by MarwanMR1** [comment]
Hi .. it worked. Thank you.

I had to add 
CURLOPT_SSL_VERIFYPEER => false
to the options array in performRequest though. Without it, I get NULL

**Comment by J7mbo** [comment]
@MarwanMR1 Having to do that is due to a cURL certificate issue - see [this issue](https://github.com/J7mbo/twitter-api-php/issues/14), and all related issues in there, for more info.
