### ISSUE TITLE
Sort by encoded key

### ISSUE THREAD

**Issue by rdlowrey** [J7mbo/twitter-api-php#12]
In your `buildBaseString()` function at [Line 232](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L232) you're sorting the parameters before encoding their keys. If you look at step 2 on Twitter's [*Creating a signature*](https://dev.twitter.com/docs/auth/creating-signature) page you'll see that you should actually: 

> Sort the list of parameters alphabetically[1] by encoded key[2]. 

You need to urlencode the keys before sorting. This will almost never create a problem if you sort before encoding but the potential exists and the order should be fixed.

**Comment by J7mbo** [comment]
I think this is done now, almost 2 years later.
