### ISSUE TITLE
Timestamp out of bound error

### ISSUE THREAD

**Issue by esraa-saady** [J7mbo/twitter-api-php#124]
Hi..
I'm getting this error

{"errors":[{"code":135,"message":"Timestamp out of bounds."}]}{"errors":[{"code":135,"message":"Timestamp out of bounds."}]}

and this is my code:

<?php
ini_set('display_errors', 1);
require_once('TwitterAPIExchange.php');

/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
    'oauth_access_token' => "####",
    'oauth_access_token_secret' => "####",
    'consumer_key' => "######",
    'consumer_secret' => "######"
);

/** URL for REST request, see: https://dev.twitter.com/docs/api/1.1/ **/
$url = 'https://api.twitter.com/1.1/blocks/create.json';
$requestMethod = 'POST';

/** POST fields required by the URL above. See relevant docs as above **/
$postfields = array(
    'screen_name' => 'usernameToBlock', 
    'skip_status' => '1'
);

/** Perform a POST request and echo the response **/
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();

and i didn't find any solution.
any help ?

**Comment by J7mbo** [comment]
Can you show the simplified code that you are using?

**Comment by esraa-saady** [comment]
edited... sorry

**Comment by glenscott** [comment]
This error is almost certainly because your system clock is not correct.
It is either set too far in the past, or too far in the future.  Either
case would trigger the Timestamp out of bounds error.

**Comment by esraa-saady** [comment]
Thanks @glenscott, but what should i do?

**Comment by glenscott** [comment]
Set your clock to the correct time :). Use NTP or something similar to keep
it in sync.

This is an issue with your system rather than the Twitter library.

**Comment by J7mbo** [comment]
Closing as no response from OP and it's not an issue with this library specifically. The *very first* link of a google search for "twitter api timestamp out of bounds" is [this](https://twittercommunity.com/t/timestamp-out-of-bounds/287/3), containing:

> If you're getting a timestamp "out of bounds" error it means that your system clock is either set too far in the future or too far in the past. Make sure that the code you're using is converting your local time to GMT before converting to epoch time in seconds. Also ensure that your system clock is accurate and not running behind or ahead. You can determine the time that Twitter's servers are set to by looking at the "Date" HTTP header returned in every response.

Of course if there are any further issues... please feel free to open another issue or comment below.
