### ISSUE TITLE
Unexpected character in input: '\' on line 296

### ISSUE THREAD

**Issue by EricRWNY** [J7mbo/twitter-api-php#125]
Hi I set this up on my site (in the dir indicated in my App settings) and am receiving these errors:

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /path_to_my_code/TwitterAPIExchange.php on line 296

Fatal error: Uncaught exception 'Exception' with message 'error setting certificate verify locations: CAfile: /usr/local/share/certs/ca-root-nss.crt CApath: none ' in /path_to_my_code/TwitterAPIExchange.php:296 Stack trace: #0 /path_to_my_code/index.php(22): TwitterAPIExchange->performRequest() #1 {main} thrown in /path_to_my_code/TwitterAPIExchange.php on line 296

Here is my index.php file:

<?php
require_once('./TwitterAPIExchange.php');
$settings = array(
    'oauth_access_token' => "redacted",
    'oauth_access_token_secret' => "redacted",
    'consumer_key' => "redacted",
    'consumer_secret' => "redacted"
);
$url = 'https://api.twitter.com/1.1/search/tweets.json';
$getfield = '?q=from%3Anationwide88%20%23JrNation&result_type=popular';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);
$api_response = $twitter ->setGetfield($getfield)
                     ->buildOauth($url, $requestMethod)
                     ->performRequest();
echo $api_response;
?>

**Comment by J7mbo** [comment]
@EricRWNY Are you using wordpress?

**Comment by EricRWNY** [comment]
I have WP installed in another dir, but am it's not associated with this project. I added that array to the performRequest call like this:

$url = 'https://api.twitter.com/1.1/search/tweets.json';
$getfield = '?q=from%3Anationwide88%20%23JrNation&result_type=popular';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);
$wp = array('CURLOPT_SSL_VERIFYPEER' => false);
echo $twitter ->setGetfield($getfield)
                     ->buildOauth($url, $requestMethod)
                     ->performRequest(true,$wp);

And am getting this back:
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /htdocs/work/twitter/TwitterAPIExchange.php on line 296

Warning: curl_setopt_array() [function.curl-setopt-array]: Array keys must be CURLOPT constants or equivalent integer values in /htdocs/work/twitter/TwitterAPIExchange.php on line 289

Fatal error: Uncaught exception 'Exception' with message 'error setting certificate verify locations: CAfile: /usr/local/share/certs/ca-root-nss.crt CApath: none ' in /htdocs/work/twitter/TwitterAPIExchange.php:296 Stack trace: #0 /htdocs/work/twitter/index.php(23): TwitterAPIExchange->performRequest(true, Array) #1 {main} thrown in /htdocs/work/twitter/TwitterAPIExchange.php on line 296

Thanks!

**Comment by J7mbo** [comment]
My bad - remove the string characters and make it just CURLOPT_SSL_VERIFYPEER.

**Comment by EricRWNY** [comment]
That worked. I'm getting it to print now. Although I still get "Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /path/to/code/TwitterAPIExchange.php on line 296" in front of the twitter data. I wouldn't think that WP in another dir would affect this. Is it messing with the authentication with my domain?
Thanks for looking at this!

**Comment by J7mbo** [comment]
So the cURL fix is just to prove that the issue is with your cUrL certificate configuration... You need to set up your cURL certificate properly so that you don't get that error - setting verify peer to false can allow MiTM attacks. 

If you don't care about security (you use Wordpress ;-)) that's no problem, otherwise I recommend fixing that (Google is your friend) so you don't have to disable peer verification.

As for the backward slash, that's just the base namespace. You need to be on, *at minimum*, PHP 5.3 - which is end of life now anyway. You need to upgrade your version of PHP, but you can disable warnings of you wish (not recommended). Your version of PHP must be so many years old :-)

**Comment by EricRWNY** [comment]
Ah okay thank you for the follow up. I'll look into it. Glad to know it's all in my setup. Thank you for all the help!

**Comment by aniagarwal97** [comment]
Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in C:\xampp\htdocs\Twitter\TwitterAPIExchange.php on line 243
it is still showing this error.
