### ISSUE TITLE
Implement versioning

### ISSUE THREAD

**Issue by iagdotme** [J7mbo/twitter-api-php#126]
Would you be able to add version numbers to the top comments of TwitterAPIExchange.php?
It will be easier to check if my current version is out of date with the current one here.

**Comment by J7mbo** [comment]
Hey Ian, yep, makes sense. I'll also put a badge at the top of README.md saying the latest stable version available.

**Comment by iagdotme** [comment]
Great, thanks for this.

**Comment by PunKeel** [comment]
:+1:

**Comment by J7mbo** [comment]
If you could check the [develop](https://github.com/J7mbo/twitter-api-php/tree/develop) branch and let me know if that's what you want guys, I'll merge into master. Thanks!

**Comment by iagdotme** [comment]
Just looked, and it's perfect. Thanks!
