### ISSUE TITLE
Packagist update

### ISSUE THREAD

**Issue by PeeHaa** [J7mbo/twitter-api-php#127]
Can you please update packagist with the new releases?

I just hacked in error handling only to find out it is already tagged and released just not updated on packagist.

![hqdefault](https://cloud.githubusercontent.com/assets/1330296/7897923/bb1d2200-06ef-11e5-9fc2-9cc0eaaa823c.jpg)

**Comment by J7mbo** [comment]
@PeeHaa Done!

**Comment by PeeHaa** [comment]
![futurama_bender](https://cloud.githubusercontent.com/assets/1330296/8261885/4bb974d8-16ce-11e5-98fc-7be5793e6e3f.jpg)
