### ISSUE TITLE
Could not authenticate you

### ISSUE THREAD

**Issue by wilcor** [J7mbo/twitter-api-php#133]
hi,
i want to post a tweet but i got the error : 
 {"errors":[{"code":32,"message":"Could not authenticate you."}]}

this is my code

 $settings = array(
          'oauth_access_token' => $oauth_token,
          'oauth_access_token_secret' =>$this->oauth_token_secret ,
          'consumer_key' =>  $this->consumerPublic[$this->settings->network],
          'consumer_secret' =>  $this->consumerSecret[$this->settings->network]
      );
      $postfields = array();      
      foreach($urlParams as $key=>$value) { 
        if ( strpos($key, "?") === 0 ) {
          $key =substr($key,1);
        }
        $postfields[$key] = $value;      
      }
      error_log("SocialJson : "  .  print_r($postfields,true) . "\n", 3, "/var/www/html/vooffdesa/logs/vooff-info.log"); 
      error_log("SocialJson : "  .  print_r($settings,true) . "\n", 3, "/var/www/html/vooffdesa/logs/vooff-info.log"); 
      $twitter = new TwitterAPIExchange($settings);
      $socialJson = $twitter->buildOauth($this->path, $_GET['method'])->setPostfields($postfields)->performRequest(true, array (CURLOPT_SSL_VERIFYPEER => false)); 

where:
$options :  
 Array
(
    [10023] => Array
        (
            [0] => Authorization: OAuth XXXXXXXXXXXXXXXX
            [1] => Expect:
            [2] => Content-Length: 0
            [3] => Content-Type:application/x-www-form-urlencoded
        )

    [42] =>
    [10002] => https://api.twitter.com/1.1/statuses/update.json
    [19913] => 1
    [13] => 10
    [64] =>
    [10015] => include_entities=1&status=hola+hola
)

Hope you can help me.

thanks 

Willy

**Comment by J7mbo** [comment]
Hi, you don't say what's in the `$urlParams` array. To debug this, I'll need a very simple example of what the parameters you're passing in to the object, and the lines of code you're doing to make the request.

**Comment by wilcor** [comment]
hi J7mbo,

thanks for the response, here the code
$settings = array(
'oauth_access_token' => $oauth_token,
'oauth_access_token_secret' =>$this->oauth_token_secret ,
'consumer_key' => $this->consumerPublic[$this->settings->network],
'consumer_secret' => $this->consumerSecret[$this->settings->network]
);
$postfields = array();

foreach($urlParams as $key=>$value) { 
if ( strpos($key, "?") === 0 ) {
$key =substr($key,1);
}
$postfields[$key] = $value;
}
$twitter = new TwitterAPIExchange($settings);
$socialJson = $twitter->buildOauth($this->path, $_GET['method'])->setPostfields($postfields)->performRequest(true, array (CURLOPT_SSL_VERIFYPEER => false));

variables value:
urlParams : Array
(
    [?include_entities] => 1
    [status] => #Violencia mucha violenciaaaa, help......
    [callback] =>
)

$this->path, 
https://api.twitter.com/1.1/statuses/update.json

$_GET['method'] 
post

$options, this variable exist inside performRequest, I add it Content-Length and Content-Type:application/x-www-form-urlencoded but the same error occurred

Array
(
[10023] => Array
(
[0] => Authorization: OAuth XXXXXXXXXXXXXXXX
[1] => Expect:
[2] => Content-Length: 0
[3] => Content-Type:application/x-www-form-urlencoded
)

[42] =>
[10002] => https://api.twitter.com/1.1/statuses/update.json
[19913] => 1
[13] => 10
[64] =>
[10015] => include_entities=1&status=hola+hola
)

thanks 

willy

**Comment by J7mbo** [comment]
Can you give me your code, without any extras?

It should be about 5 lines to show what isn't working. I need to see: your post fields, your request using the object methods, and that's it. Anything else won't help.

This means *no $_GET* (how am I supposed to know what you're passing in!?) and *no $_POST*.

As of right now, *I can't copy and paste your code and have it immediately running on my machine*.

Again, this urlParams variable - that isn't part of the API call - replace *all* of the non-api stuff with a simple, reproducible example and I may be able to help you :-)

**Comment by J7mbo** [comment]
Closing as no update here.
