### ISSUE TITLE
Is there a way to see errors?

### ISSUE THREAD

**Issue by hepaestus** [J7mbo/twitter-api-php#135]
Can I  do something to get some error info or debugging output? Things seem to work but I am not able to actually post any tweets and I am unclear as to why. 
Thanks.
P.

**Comment by J7mbo** [comment]
If there are any curl errors, you'll see these because of [this line](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L297). 

How do they "seem to work", but it's not working? Can you make sure that the line I linked above is in your version of the code as well?

**Comment by hepaestus** [comment]
I re-read the code and I can see now what you mean. Thank you. Please close this ticket.

**Comment by J7mbo** [comment]
No problem :-)
