### ISSUE TITLE
DELETE request possible?

### ISSUE THREAD

**Issue by fdask** [J7mbo/twitter-api-php#138]
I'm trying to figure out if I can get this library to issue a DELETE request... trying to access the api endpoint described here:  https://dev.twitter.com/ads/reference/delete/accounts/:account_id/cards/app_download/:card_id

Haven't had any luck so far tinkering in the code.  Any insight?

**Comment by glenscott** [comment]
I've added some experimental code for supporting DELETE and PUT methods in this pull request:

https://github.com/J7mbo/twitter-api-php/pull/139

Without access to the Ads API, I can't test directly so if you could provide any feedback on this, it would be appreciated.

**Comment by fdask** [comment]
$url = "https://ads-api.twitter.com/0/accounts/$TWITTER_ACCOUNT_ID/cards/website";
$requestMethod = "DELETE";

$params = array(
   'card_id' => 's5dg'
);

$twitter = new TwitterAPIExchange($TWITTER_SETTINGS);
$result = $twitter->buildOauth($url, $requestMethod)->setPostfields($params)->performRequest();

Gives me an error.

{"errors":[{"code":"UNAUTHORIZED_ACCESS","message":"This request is not properly authenticated"}],"request":{"params":{}}}

I'm able to use the same credentials, same endpoint, and do a GET request to list my website cards just fine.   Not sure whats up.

**Comment by fdask** [comment]
Also tried leaving out the params, putting the card_id directly on the end of the URL as the docs show.  Left out the setPostfields call.  Same issue.

**Comment by fdask** [comment]
Could have something to do with the access level I've got... I'm only on the developer level which apparently has some restrictions.  Hrmm.

**Comment by fdask** [comment]
$result = $twitter->buildOauth($url, $requestMethod)->performRequest(true, array(CURLOPT_CUSTOMREQUEST => "DELETE"));

adding the curl setting to change the request to a delete, worked!

**Comment by glenscott** [comment]
@fdask apologies, I forgot to mention you needed the CURLOPT_CUSTOMREQUEST option.  I'll amend the code to add this option automatically on DELETE methods so you won't have to pass it in.

**Comment by J7mbo** [comment]
This is a really really old one, do you guys still want it? I've added PUT for someone else, but not DELETE, which should be really simple. Please feel free to submit a PR into develop with tests if needed. Closing for now... cheers :-)
