### ISSUE TITLE
MitM security vulnerability

### ISSUE THREAD

**Issue by rdlowrey** [J7mbo/twitter-api-php#14]
You should never, ever [disable SSL peer verification](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L197) unless you're cool with me hijacking your twitter API credentials. But seriously, this is a really bad security practice. Curl uses a certificate authority file that should have no problem verifying the twitter cert. There's no reason to disable this.

**Comment by peter-mw** [comment]
This lib should have a setting to disable the SSL check

**Comment by J7mbo** [comment]
@peter-mw It does :-)

https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L257

**Highly recommended** to sort your certs out, though. It's not hard.

**Comment by Fedcomp** [comment]
So does it throws exception now if ssl verification failed?

**Comment by J7mbo** [comment]
Exception is thrown if there was a `curl_error()` which includes ssl verification error... but you can pass in verify false if you need to :-)

**Comment by peter-mw** [comment]
cool :) thanks @J7mbo  i will update my version now
