### ISSUE TITLE
boolean param causes 401?

### ISSUE THREAD

**Issue by RonaldPK** [J7mbo/twitter-api-php#140]
Whenever I add the `possibly_sensitive` parameter to a status update and set it to boolean `false`, Twitter will return a 401 status code and error 32, "Could not authenticate you". If I set it to string `'false'`, everything is fine. 

My code:
```php
$oApi = new TwitterAPIExchange(array(
		'oauth_access_token' => OAUTH_TOKEN,
		'oauth_access_token_secret' => OAUTH_TOKEN_SECRET,
		'consumer_key'    => CONSUMER_KEY,
		'consumer_secret' => CONSUMER_SECRET
));
$response = $oApi->buildOauth('https://api.twitter.com/1.1/statuses/update.json', 'POST')
   ->setPostfields(array(
		'status'			=> 'status message here',
		'possibly_sensitive'	=> false
   ))
   ->performRequest();
```
(I haven't checked whether Twitter actually sets `possibly_sensitive` to `false` when I send a string... )

For now I'm simply not sending the parameter, as it defaults to false anyway.

**Comment by glenscott** [comment]
I can see why this is happening -- internally, the library is converting the boolean to an empty string when creating the oAuth base signature.  We could put in a fix for that 

OR

we could update the documentation to make it clear that post field values have to be strings.

@RonaldPK setting to string 'false' will work as expected.

**Comment by RonaldPK** [comment]
Well, in PHP `'false' == true` , so expecting a string would not be expected behaviour, imho...

**Comment by glenscott** [comment]
The Twitter API only deals with string parameters, which is why I suggested updating the documentation to make this explicit.

However, @J7mbo needs to make a call on this.

**Comment by J7mbo** [comment]
The API endpoint provided by Twitter expects a boolean so we should expect to be able to take in the boolean that it asks for. Responsibility is on our end. Guessing this is to do with the `rawurlencode` that you pointed out Glen?

**Comment by glenscott** [comment]
@J7mbo yes, indeed.  rawurlencode(false) equates to an empty string, so we'll need to convert booleans to strings if we detect them.

**Comment by J7mbo** [comment]
I'll merge from develop to master soon and release as 1.0.5.
