### ISSUE TITLE
Problems with media uploading

### ISSUE THREAD

**Issue by krixmeister** [J7mbo/twitter-api-php#146]
Is there a working example of uploading media using TwitterAPIExchange? I can't get it to work, and am assuming the problem is something I'm doing. I can GET requests from Twitter, and can POST a status update, but when I try to POST media I get the response:

{"errors":[{"code":32,"message":"Could not authenticate you."}]}

Here's the relevant code:

$postfields = array('status' => 'Hi there!');
$url = "https://api.twitter.com/1.1/statuses/update.json";
$requestMethod = 'POST';
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod);
->setPostfields($postfields)
->performRequest();
// this works

$handle = fopen($img_url, 'rb'); //$img_url is defined earlier
$img = new Imagick();
$img->readImageFile($handle);
$img->resizeImage(128, 128, 0, 0);

$postfields = array('media' => $img);
$url = "https://upload.twitter.com/1.1/media/upload.json";
$requestMethod = 'POST';
$twitter = new TwitterAPIExchange($settings);
$response = $twitter->buildOauth($url, $requestMethod)
->setPostfields($postfields)
->performRequest();
//this returns "{"errors":[{"code":32,"message":"Could not authenticate you."}]}"`

**Comment by J7mbo** [comment]
Hi, one of the tests shows media upload working. Check out [testMediaUpload()](https://github.com/J7mbo/twitter-api-php/blob/master/test/TwitterAPIExchangeTest.php#L165-L194), maybe that will help you?

From the [docs](https://dev.twitter.com/rest/reference/post/media/upload): 

> You may either upload the raw binary of the file or its base64-encoded contents.

Perhaps you're missing the base64 encoding? Try similar code to that of the test above and let me know.

**Comment by krixmeister** [comment]
Thanks - with a bit of looking at the testMediaUpload() function I got it to work - that was very helpful, thanks. I did have to add base64 encoding, which is strange as according to the docs, by using 'media' instead of 'media_data' you shouldn't need to base64 encode. But oh well, it is working now.

Thanks for your help.
