### ISSUE TITLE
Invalid or expired token error.

### ISSUE THREAD

**Issue by mehmetcoskun** [J7mbo/twitter-api-php#148]
Hello,

I get following error:

{"errors":[{"code":89,"message":"Invalid or expired token."}]}

I see that it is because the token expires. Do below token parameters's values change for every request?

~~~
oauth_access_token
oauth_access_token_secret
~~~

If so, how to get new ones? Or if I miss something, what should I do to overcome invalid/expired token?

Greetings,

Mehmet

**Comment by mehmetcoskun** [comment]
I have fixed it, it was my error to use wrong values.

During the fix, I come across this:

https://github.com/jublonet/codebird-php

That it shows how to authenticate if you don't have OAuth token and secret. Does twitter-api-php need same approach?

Regards,

Mehmet.

**Comment by J7mbo** [comment]
Glad you got it fixed.
