### ISSUE TITLE
clear post/get fields

### ISSUE THREAD

**Issue by tostercx** [J7mbo/twitter-api-php#149]
Hi,

I like to reuse the same '$twitter' instance after initializing it with the settings once, The works fine as long as I do only POST requests or only GET. If I use a GET after a POST tho, the library thinks I'm trying to send both.

Could we add a method to clear get/post request data somehow? Or maybe delete both after performRequest has been called? Making new instances each time seems redundant...

**Comment by BugHunter2k** [comment]
Something like this?
https://github.com/BugHunter2k/twitter-api-php/commit/57b7d679bec7d2d00d4614596ef5f194307e7459

**Comment by tostercx** [comment]
Oh look, there's already a pull request for it :+1:
Yep, exactly like that!

**Comment by J7mbo** [comment]
As commented on that PR, the user shouldn't have to call `reset()` though, it should be automatic. I've opened a new issue for collaboration at #150.
