### ISSUE TITLE
Allow object re-use

### ISSUE THREAD

**Issue by J7mbo** [J7mbo/twitter-api-php#150]
There needs to be an **automatic** way of resetting the fields so the object can be re-used. A `reset()` method shouldn't have to be called by the end-user.

**Comment by tostercx** [comment]
We could reset get when setting post and vice-versa. That way the last one set will be the one that's sent.
https://github.com/tostercx/twitter-api-php/commit/fcb52410fe6301d50c5f337c9dc259c0df991ae8

Seems to be working.

**Comment by BugHunter2k** [comment]
IMHO Better: reset the fields directly after sending request
https://github.com/BugHunter2k/twitter-api-php/commit/9dda72e374fc3c93de363858f26b80e477d0f812

**Comment by J7mbo** [comment]
#169 was the new one. PRS do need to go onto develop, with their own tests, but once it does perhaps we can get something working for this. Closing for now as it's really old but please feel free to submit a new issue / PR if you like.
