### ISSUE TITLE
Microsoft Azure

### ISSUE THREAD

**Issue by jayaneetha** [J7mbo/twitter-api-php#152]
I installed Twitter API PHP library through composer and I was able to run the application in my localhost (MAMP). But when I deploy the application on Azure cloud as a web app, it did not work. I checked the cURL module and it is on. 
Here is the code I tried;
```
require __DIR__ . '/vendor/autoload.php';

require 'setting.php';

$twitter = new TwitterAPIExchange($settings);


if (isset($_GET['max_id'])) {
    $getfield = '?q=#' . $_GET['q'] . '&count=30&max_id=' . $_GET['max_id'];
} else {
    $getfield = '?q=#' . $_GET['q'] . '&count=30';
}
$url = 'https://api.twitter.com/1.1/search/tweets.json';
$requestMethod = 'GET';
$response = $twitter->setGetfield($getfield)
    ->buildOauth($url, $requestMethod)
    ->performRequest();
header('Content-Type: application/json');
echo $response;
```
Have you ever tried this API on an Azure Cloud? or What may be the possible cause for the error.

**Comment by J7mbo** [comment]
I haven't tried this on Azure Cloud. Can you provide what the specific error is? You say "it did not work". Do you get a null response? Do you get an `\Exception`? Do you have error logging (and displaying) enabled?

**Comment by jayaneetha** [comment]
No any exceptions displaying. I've enabled the error logging but it does not display any error either. As for my feeling, It does not communicating with twitter API. But cannot find out where and why. cURL is also active.

**Comment by jayaneetha** [comment]
I Found the bug! Twitter API needs SSL to communicate and Azure WebApps does not have SSL enabled. We have manually add a SSL certificate to Azure.
