### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by webselfsrl** [J7mbo/twitter-api-php#156]
Hello,

doing a request with your great Lib I have this error:

 Uncaught exception 'Exception' with message 'Protocol "https" not supported or disabled in libcurl

I know that in my hosting is not allowed the cURL HTTPS option.

I'm wondering if there is a way to convert the cURL request in a file_get_content request in your Lib.

Let me know,

Best Regards

**Comment by A973C** [comment]
Hi,
I had the same issue. Here is a workaround:
- Edit "TwitterAPIExchange.php" file
- Line 277, you'll find CURL options
- Add "CURLOPT_SSL_VERIFYPEER => false,"

Cheers!

**Comment by J7mbo** [comment]
Disabling peer verification opens you up to MiTM attacks. See [this issue](https://github.com/J7mbo/twitter-api-php/issues/14).

However, if you do require that line and don't care about security, then you can pass that in as a parameter to the [performRequest()](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L265) method.

**Comment by A973C** [comment]
This is just a workaround to test/use your framework.

Whats your solution to prevent this issue?

**Comment by J7mbo** [comment]
The solution would be not to use restrictive hosting that doesn't allow https via cURL. That's a very old fashioned way of doing things.
