### ISSUE TITLE
Not able to use Twitter API's member related API functions

### ISSUE THREAD

**Issue by coder426** [J7mbo/twitter-api-php#159]
Hi,

I am using your script for one of the twitter app. It is working good when i use most of the API functions like getlists, block member, follow, unfollow, get-list-members etc but i am getting constant issue if i try to add a member in specific list or if i try to destroy a member from list.

Talking about this specific function:
https://dev.twitter.com/rest/reference/post/lists/destroy

Issue:
[code] => 112 [message] => You must specify either a list ID or a slug and owner. 

I am getting this message even i hardcode the listID or ownerId and used all possible combination required by that API function.

I also dropped same issue on twitter community but no luck yet.
https://twittercommunity.com/t/error-112-you-must-specify-either-a-list-id-or-a-slug-and-owner/53007

Can you please verify or help how we can use that function using your API script? I tried some of the other list-member related functions but those which have Get method are working while with POST method are not working.

Hope, you can provide a solution.

Thanks,

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.

**Comment by testgonzo** [comment]
It's October, 2020, I am having this issue still today.  Just opened issue #294 

https://github.com/J7mbo/twitter-api-php/issues/294https://github.com/J7mbo/twitter-api-php/issues/294
