### ISSUE TITLE
"Could not authenticate you" error when sending multiple tweets

### ISSUE THREAD

**Issue by seanzolanski** [J7mbo/twitter-api-php#161]
I'm trying to build out a forum thread tweet bot, but sending multiple tweets back to back causes half of them to fail with a "Could not authenticate you" error. This is the code I'm using to actually send the requests:

    while($data = mysql_fetch_assoc($result)) {
			$mediaID = getImage($SECTION_NAMES[$data['forum_id']] . ' ' . $data['title']);

			$postfields = array(
				'status' => html_entity_decode('[' . $prefix . '] "' . $data['title'] . '" | ' . 'SITE_URL' . $data['tid'] . '-' . $data['title_seo'] . '/')
			);
			
			if($mediaID <> '') {
				$postfields['media_ids'] = $mediaID;
			}
			
			$req = $twitter->buildOauth($url, $requestMethod)
						 ->setPostfields($postfields)
                                                 ->performRequest();
		}

I very well could be just screwing something up, but I can't for the life of me figure out what it could be. The last time I tried, there were 5 requests and the first and third failed. I've tried re-initializing the $twitter variable within the loop as well, but that made no difference.

**Comment by J7mbo** [comment]
Sorry for the delay in this.

Nope, you're not screwing anything up. The current implementation unfortunately requires you to create and set up a new `\TwitterApiExchange` object each time. Do that and it'll work.
