### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by dregad** [J7mbo/twitter-api-php#162]
Greetings

I just downloaded the latest release (1.0.5) today, and just noticed that in the header comment [the version is listed as 1.0.4](https://github.com/J7mbo/twitter-api-php/blob/1.0.5/TwitterAPIExchange.php#L12).

**Comment by J7mbo** [comment]
Thanks for the message, will update with the next release.

**Comment by J7mbo** [comment]
Closing, will update labels properly in next update.
