### ISSUE TITLE
Sorry, that page does not exist..

### ISSUE THREAD

**Issue by uiktiomasfeliz** [J7mbo/twitter-api-php#163]
Hello,
I tried to use this plugin and with the example work's fine. The problem is when i try to do this:

    public function __construct() {

            $this->trace = new traces();

            $this->settings = array(
                'oauth_access_token' => "xxxxxxxxxxxx",
                'oauth_access_token_secret' => "xxxxxxxxxxxx",
                'consumer_key' => "xxxxxxxxxxxx",
                'consumer_secret' => "xxxxxxxxxxxx"
            );

        }

public function getTwitterSearch($search){

          echo "search -> " . $search  . "\r\n";

          $this->trace->traceToFile("Class: " . get_class($this) . " Function: " . __FUNCTION__ . " Parameteres: " .  implode(",", func_get_args()));

          $url = 'https://api.twitter.com/1.1/search/tweets.json';
          /*$getfield ='?q=' . $search . '&count=100';*/
          $getfield ='?q=#hybridcloud&result_type=recent';
          $requestMethod = 'GET';

          $twitter = new TwitterAPIExchange($this->settings);
          $response = $twitter->setGetfield($getfield)
              ->buildOauth($url, $requestMethod)
              ->performRequest();

          return ($response);

        }

And this is what i get:
{"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}

Also tried encoding the search query, and add in $options "CURLOPT_SSL_VERIFYPEER => false" , same response

**Comment by mg-sd** [comment]
I had this issue with a 'screen_name=' parameter in the URL, it turned out the user had changed their twitter screen name.
