### ISSUE TITLE
How can I get only tweets (not replies)?

### ISSUE THREAD

**Issue by ernestby** [J7mbo/twitter-api-php#164]
Hi there,

I need to get only tweets from my account (not replies like "@username hello you!"). How can I do that usign this lib?

Thanks in advance.

**Comment by J7mbo** [comment]
Can you show me the code you're currently using that's not working, and we'll go from there.

**Comment by ernestby** [comment]
Hi J7mbo, 

I've resolved it with regex. Thank you for your reply.

$tweets = array();
	if ($response = $iaTwitter
		->setGetField('?screen_name=' . $iaCore->get('twitter_feed_username') . '&count=' . $iaCore->get('twitter_feed_number_of_tweets'))
		->buildOauth('https://api.twitter.com/1.1/statuses/user_timeline.json', 'GET')
		->performRequest())
	{
		$response = json_decode($response);
		if (!isset($response->errors))
		{
			foreach ($response as $tweet)
			{
				$tweets[] = array(
					'created_at' => $tweet->created_at,
					'name' => $tweet->user->name,
					'image' => $tweet->user->profile_image_url,
					'screen_name' => $tweet->user->screen_name,
					'text' => preg_replace('#((http|https):\/\/[a-z0-9_\.\-\+\&\!\#\~\/\,]+)#i', '<a href="$1" target="_blank">$1</a>', $tweet->text),
					'url' => 'http://twitter.com/' . $tweet->user->screen_name
				);
			}
		}
	}

	// deleting replies
	foreach ($tweets as $id => $tweet)
	{
		preg_match('/@(.)+/', $tweet['text'], $matches);
		if (!empty($matches[0]))
		{
			unset($tweets[$id]);
		}

	}

	$iaView->assign('timeline', $tweets);
