### ISSUE TITLE
Base64 really needed?

### ISSUE THREAD

**Issue by anteksiler** [J7mbo/twitter-api-php#167]
I see that you have added base64 to oauth signature here:

    $oauth_signature = base64_encode(hash_hmac('sha1', $base_info, $composite_key, true));

Twitter says it only needs: HMAC-SHA1
https://dev.twitter.com/oauth/overview/creating-signatures

**Comment by J7mbo** [comment]
Well, the tests pass and it works for everyone! :-) If you think there should be a change, you can play about with the code and run the tests to see if they still work, and if they do, please feel free to submit a PR into develop and we'll get it merged in.
