### ISSUE TITLE
Status is duplicate after destroy same content status

### ISSUE THREAD

**Issue by nvcken** [J7mbo/twitter-api-php#171]
sometimes I got weird error.
After called destroy specific status by id.
Then call update status with same content of above deleted status, I get status is duplicated error.
is this maybe twitter API problem?
Need experience help, plz

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.
