### ISSUE TITLE
Suggestion for localhost environment 

### ISSUE THREAD

**Issue by Antibioticvz** [J7mbo/twitter-api-php#173]
I have to add (Line 298)
```php
curl_setopt($feed, CURLOPT_CAINFO, "B:/Bitnami/wordpress/php/cacert.pem");
```
to make it work on my localhost but I'm sure it should be a better solution... Looking for an advice how to improve my own code to prevent this kind of issue.

**Comment by J7mbo** [comment]
You need to set up cURL properly on your machine so it knows where to find your pem. I think you can do this via command line calls.

However, if you look at the [method signature](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L265) of performRequest(), you'll see you can pass a second parameter which is an array of cURL parameters.

You would call:

    performRequest(true, ['CURLOPT_CAINFO' => "B:/Bitnami/wordpress/php/cacert.pem"]);

**Comment by Antibioticvz** [comment]
Thanks for that! Is it a good practice to provide cacert.pem file in my plugin project ? Just in case that someone wanna use it on localhost.

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.
