### ISSUE TITLE
 Get number of followers of followers - Twitter API 

### ISSUE THREAD

**Issue by antoparis** [J7mbo/twitter-api-php#176]
I try to found the followers of the followers of a user, to know the popularity of the user. I use twython and It's my code to find this:
```
`user_followers = t.get_followers_list(user_id = from_user_id, count = 200)
  follower_followers_sum=0
 for follower in user_followers['users']:
                     follower_followers_sum+=follower['followers_count']]`
```

It runs but  I am running into the API rate limits. For example, if I have 1614 users, This can calculate the followers of the followers for the first 14 users and then stopped. There's a method that find the followers_count of the followers of a user without finding the follower id or screen_name (that has a strict limits)? Or that can't reach the rate limit

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.
