### ISSUE TITLE
Getting image

### ISSUE THREAD

**Issue by Idhanta** [J7mbo/twitter-api-php#180]
Is it possible to get images from tweets?
If so, how?

**Comment by YoniSL** [comment]
Loop over the result from /search/tweets.json request and check the entities array.
It seems I can not apply a filter though. as the filter is applied like filter:images where the setGetField function only checks for = and ? characters.

https://api.twitter.com/1.1/search/tweets.json?from:someuser&filter:images

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.
