### ISSUE TITLE
Posting image with tweet

### ISSUE THREAD

**Issue by cbielich** [J7mbo/twitter-api-php#181]
Maybe I am missing something but is there a way to post an image with a tweet with your code?

As an example code I am trying something like this

require_once('TwitterAPIExchange.php');

/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
    'oauth_access_token' => "xxx",
    'oauth_access_token_secret' => "xxx",
    'consumer_key' => "xxx",
    'consumer_secret' => "xxx"
);
$url = "https://api.twitter.com/1.1/statuses/update.json";
 
$requestMethod = 'POST'; 

$twimage = 'image.jpg';

$postfields = array(
	'media[]' => "@{$twimage}",
    'status' => 'Testing Twitter app'
);
 
$twitter = new TwitterAPIExchange($settings);
 
$response = $twitter->buildOauth($url, $requestMethod)
                   ->setPostfields($postfields)
                   ->performRequest();
 
print_r($response);

**Comment by BugHunter2k** [comment]
You have to upload the image first. The api gives you an ID wich you send as media with yout post. eg:
`
// Upload image to twitter
        $url = "https://upload.twitter.com/1.1/media/upload.json";
        $method = "POST";
        $params = array(
            "media_data" => $image,
        );

        $json = $this->api->resetFields()->setPostfields($params)
                        ->buildOauth($url, $method)
                        ->performRequest();
// Result is a json string
        $res = json_decode($json);
// Extract media id
        $id = $res->media_id_string;

// Send tweet with uploaded image
$params= array('media_ids' => $id);
$json = $this->api->resetFields()->setPostfields($params)
                        ->buildOauth($url, $method)
                        ->performRequest();

`

**Comment by cbielich** [comment]
What is `$this`? and where does my `$settings` go so I cant send my tokens and such.

**Comment by BugHunter2k** [comment]
Oh, sorry 
Just copied some line from my class. $this is the twitter class. You can use $twitter in your case.
Your settings will go in the initialization like you have done this far.

**Comment by cbielich** [comment]
I ended up going with Codebird and it works great!

**Comment by helloarpitgshah** [comment]
Hey,

I got the response with the media_id_string but whenever I can check with the twitter, I can't find the images.

Can you please let me know about the issues?

Thanks,
Arpit G Shah

**Comment by gnanasekaranl** [comment]
HI ,
 I can't tweet with image. I use above code i get API not defined error

ex: $json = $this->api

**Comment by BugHunter2k** [comment]
Code above was just a little copy past out of a bigger project. Made a little modification with api-init. Haven't tested the changes, but give it a try.

**Comment by gnanasekaranl** [comment]
@BugHunter2k Not working. give me any other option

**Comment by J7mbo** [comment]
Take a look at the tests, they're usually a great indicator of how to do things.

Firstly, upload the image. Here's [testMediaUpload()](https://github.com/J7mbo/twitter-api-php/blob/master/test/TwitterAPIExchangeTest.php#L165-L194).

Then, the [following test](https://github.com/J7mbo/twitter-api-php/blob/master/test/TwitterAPIExchangeTest.php#L196-L230) creates a tweet with the id of the uploaded image.

Give that a try, they work otherwise the tests would be failing for everyone.

**Comment by gnanasekaranl** [comment]
Thanks for reply.
This test function, how can I run the function. Give me a example

**Comment by gnanasekaranl** [comment]
Finally I did.

$file = file_get_contents(__DIR__ . '/img/logo.png');
        $data = base64_encode($file);

// Upload image to twitter
$url = "https://upload.twitter.com/1.1/media/upload.json";
$method = "POST";
$params = array(
    "media_data" => $data,
);


$json = $twitter
            ->buildOauth($url, $method)
            ->setPostfields($params)            
            ->performRequest();

// Result is a json string
$res = json_decode($json);
// Extract media id
$id = $res->media_id_string;



$url = 'https://api.twitter.com/1.1/statuses/update.json'; 
$requestMethod = 'POST';
$postfields = array(
    'media_ids'  => $id,
    'status' => 'This is machine test' ); 

if(strlen($postfields['status']) <= 140)
{
//$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();
}else{
    echo "140 char exceed";
}

**Comment by J7mbo** [comment]
Hi, this is an old one. I'm just going through and cleaning up issues, although if you still need help, please feel free to reopen a new issue. Thanks.

**Comment by cbielich** [comment]
I cant even remember what I did to fix it lol

**Comment by webboyon** [comment]
Hi all  this what got me  
twiiter  says
media 	**required** 	// really!!!   	 
media_data 	**required**

all you have to do is  create the array  and only use media_data => base64_encode(file_get_contents(...));
Working prefect for uploding image and video

**Comment by birdbreath** [comment]
Returns:

Fatal error: Uncaught Error: Call to a member function buildOauth() on null

Any 
<img width="655" alt="Screen Shot 2020-10-05 at 5 34 01 PM copy" src="https://user-images.githubusercontent.com/72421806/95146622-262ad580-0733-11eb-80f8-8ef341e790fe.png">
idea why?

**Comment by birdbreath** [comment]
line 32

**Comment by stepinnsolution2** [comment]
Did above code work?

**Comment by birdbreath** [comment]
No, but this one below did:

<?php

// include config and twitter api wrapper
require_once('TwitterAPIExchange.php');
    
    $date = date("Ymd");
    echo "$date\n";
    
    foreach (glob("/Users/robertseymour/MacBook_Local/complete/midphase/$date*.png") as $filename){
        echo "$filename exists\n";
        
    }
    echo $filename;
    
  system("/opt/local/bin/convert $filename -resize 20% -quality 10 /Users/robertseymour/MacBook_Local/complete/midphase/t.png"); 
// &> /Users/robertseymour/MacBook_Local/scripts/cron_error.log");

// settings for twitter api connection
/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
'oauth_access_token' => 
"50180715-3F7yZmwBLJouO3fa6avhW0AJG0d7Y9bfMpRWYQEkQ",
'oauth_access_token_secret' => "tLatm320LcRYh5ti4LV4iMk3eiE0zyI691XeXA71is",
'consumer_key' => "TcrdUlDdg8id1ZYjdXg",
'consumer_secret' => "CfdKClaUYtG4caUU55q7InwsYYjJH8h3u0vRhY5I");


// $file = file_get_contents("$Home/Users/robertseymour/MacBook_Local/complete/midphase/t.png");

    $file = file_get_contents("/Users/robertseymour/MacBook_Local/complete/midphase/t.png");
    
// echo "$file\n";
    
    $data = base64_encode($file);
    
    $twitter = new TwitterAPIExchange($settings);

    // Upload image to twitter
    $url = "https://upload.twitter.com/1.1/media/upload.json";
    $method = "POST";
    $params = array(
    "media_data" => $data,
    );
    
//print_r($params);
    
//echo "$url\n";
//echo "$method\n";
    
// echo "$twitter->buildOauth($url, $method)";

    $json = $twitter
    ->buildOauth($url, $method)
    ->setPostfields($params)
    ->performRequest();
    
    print_r($json);

// Result is a json string
    $res = json_decode($json);
    
// Extract media id
    $id = $res->media_id_string;

    $url = 'https://api.twitter.com/1.1/statuses/update.json';
    $method = 'POST';
    $postfields = array(
    'media_ids' => $id,
    'status' => 'Heres your new weekday BirdBreath cartoon  http://birdbreath.com #parrot #bird #cartoon #coronavirus.' );
    
    if(strlen($postfields['status']) <= 140)
    {
//$twitter = new TwitterAPIExchange($settings);
    $twitter->buildOauth($url, $method)
    ->setPostfields($postfields)
    ->performRequest();
    }else{
    echo "140 char exceed";
    }
?>

**Comment by birdbreath** [comment]
No, but this revised one did:
<img width="792" alt="php2" src="https://user-images.githubusercontent.com/72421806/149215185-2d95246f-721f-49be-a1ad-869d94eb09fc.png">
