### ISSUE TITLE
We cant do 2 or more "performRequest"

### ISSUE THREAD

**Issue by Carlosmape** [J7mbo/twitter-api-php#182]
We cant do 2 or more "performRequest" with differents methods:

```
$url = 'https://api.twitter.com/1.1/statuses/retweet/'.$id_tweet.'.json';
			$requestMethod = 'POST';
			$postfields = array();
			$jsonraw1=$this -> twitter -> buildOauth($url, $requestMethod) -> setPostfields($postfields) -> performRequest();
$url = "https://api.twitter.com/1.1/statuses/home_timeline.json";
			$getfield = "";

			$jsonraw2 =  $this -> twitter -> setGetfield($getfield)
                -> buildOauth($url, 'GET')
                -> performRequest();
```

throw an exception:
 "You can only choose get OR post fields"

We show it at line 94 and 131 in your library. We fixed it adding the following lines to performRequest() method:

`$this->postfields = NULL;
        $this->getfield = NULL;`
just before the `return $json;`

**Comment by BugHunter2k** [comment]
Solved in: https://github.com/J7mbo/twitter-api-php/pull/169

**Comment by Carlosmape** [comment]
nice!

**Comment by J7mbo** [comment]
Unfortunately the PR in question doesn't do it in the nicest way (class constants). That's just one option, though :-) I'll close for now, but if you guys want something in please feel free to make another PR into develop that uses private vars and a setter and maybe we can get something in.
