### ISSUE TITLE
Take an image from webserver

### ISSUE THREAD

**Issue by Dawa89** [J7mbo/twitter-api-php#183]
Hi,

i want to share an image from a url. Is there any way to realize this?

My code 
```
$image = 'http://domain.de/image/contentimage.jpg';
$name  = basename($image);
$status = "Picture time";
$media = "@{$image};type=image/jpg;filename={$name}";


$url = 'https://api.twitter.com/1.1/statuses/update_with_media.json';
$requestMethod = 'POST';
$postfields = array(
    'media[]'  => $media,
            'status'   => $status
);
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
    ->setPostfields($postfields)
    ->performRequest();

```
At the moment i got the following error

{"errors":[{"code":195,"message":"Missing or invalid url parameter."}]}

**Comment by J7mbo** [comment]
Currently, as far as I know, there are two ways to post an image with a tweet:

1) You upload it first, get it's ID, then post a new tweet with the image ID
2) You post a new tweet with the image url in there

Really they're the two ways of going about it. You might need to do something like the following in your own code:

1) Grab the url and download the file to a temporary file
2) Upload the file like normal, as in the examples (or test that shows it uploading in tests/)
3) Delete the temporary file
