### ISSUE TITLE
Error in POST calls with 2 or more parameters

### ISSUE THREAD

**Issue by TomCrush** [J7mbo/twitter-api-php#187]
Hi there, I can't find a solution for this issue.
All my POSTS works fine, but when I use 2 or more parameters in $postfields, like this:

`$postfields = array(
	'status' => $statustext,
	'in_reply_to_status_id' => $TweetID
);`

and then perform a POST:

`$twitter = new TwitterAPIExchange($settings);
$twitter = $twitter->buildOauth($url, $requestMethod)
->setPostfields($postfields)
->performRequest();
$return_json= json_decode($twitter, true);`

I always get {"errors":[{"message":"Could not authenticate you","code":32}]}

Is there a fix for this?
Thanks!

**Comment by J7mbo** [comment]
Could you post the exact code you're using, including the url and tweet ID basically. Thanks.

**Comment by TomCrush** [comment]
Ok, thank you for your response :)
You can test it with any tweet ID where you are mentioned. I put the user's screen_name in reply of course.

$TweetID = "715854796750721024";
$statustext= "@R5Belleza Blablabla...";

$url = "https://api.twitter.com/1.1/statuses/update.json";
$requestMethod = 'POST';

$postfields = array(
    'status' => $statustext,
    'in_reply_to_status_id' => $TweetID
);

$twitter = new TwitterAPIExchange($settings);
$twitter = $twitter->buildOauth($url, $requestMethod)
->setPostfields($postfields)
->performRequest();
$return_json= json_decode($twitter, true);

**Comment by ArjanAssink** [comment]
Hi,

Just ran into this same issue, managed to get around it by reducing the post parameters to 2. Is there anything I can supply you with to help fix this issue in a more structural way?

@TomCrush thanks for posting it with the title the way you did, this pointed me to the workaround I currently have.

**Comment by J7mbo** [comment]
Hmm, could you by any chance write a failing test for this? If you can maybe we can work together to figure out what the issue is?

**Comment by ArjanAssink** [comment]
I could give part of my code, but it looks very similar to TomCrush's. Is that not giving the error described when you test is? If not, I'll have a look and anonymize my code.

**Comment by J7mbo** [comment]
Well we know from [this passing test](https://github.com/J7mbo/twitter-api-php/blob/master/test/TwitterAPIExchangeTest.php#L210) that it isn't two or more parameters that's causing the issue. The only thing the test doesn't use is `in_reply_to_status_id`.

Can you try removing that and putting some other parameters so we can narrow it down to the exact issue? Also, I haven't checked but make sure the person's account you're replying to isn't protected perhaps.

**Comment by J7mbo** [comment]
Hi guys, I've updated the test to prove `in_reply_to_status_id` definitely works [here](https://github.com/J7mbo/twitter-api-php/blob/reply-bug/test/TwitterAPIExchangeTest.php#L212).

The code seems to be passing, so it must be something else.

@TomCrush Can you please prove that the library works for you just for posting a status, **not** with replying to one?

**Comment by ArjanAssink** [comment]
The issue with me what with sending a DM, I'll look up the use case.

**Comment by ArjanAssink** [comment]
Hmm, just tried recreating the issue sending a DM with the screen_name, user_id and text, but it works. Perhaps during my earlier use there was something violating in the text. If I manage to reproduce it in the future I will let you know, sorry. Thanks for providing this code btw, saved me a lot of work :)

**Comment by J7mbo** [comment]
No problem, glad we managed to figure it out. I'll close for now then, @TomCrush if you still have a problem please feel free to re-open.
