### ISSUE TITLE
Get Tweet for specific URL using Twitter API

### ISSUE THREAD

**Issue by cristopher-christ** [J7mbo/twitter-api-php#193]
Hi everyone ,

I need help for get count of tweet for specific URL using Twitter API. Any one have sample code to achieve that functionality for my website. I need total share tweet count for my each post.

Please help if any one have idea for that. 
Thanks,
Crish

**Comment by hugovk** [comment]
@cristopher-christ This is more of a general Twitter API question than a twitter-api-php library question, but can you be more specific? 

Have a look through https://dev.twitter.com/rest/public and see if there's a Twitter API call there for your need.
