### ISSUE TITLE
oauth_access_token_secret

### ISSUE THREAD

**Issue by ThatGamerBlue** [J7mbo/twitter-api-php#195]
Do I have to pass the oauth secret, what if I don't have it? Do I pass it anything I want to?

**Comment by J7mbo** [comment]
Sorry I didn't get around to this in time! I'm just cleaning up issues. If you still need help with this, please feel free to post, otherwise closing for now.

**Comment by ThatGamerBlue** [comment]
still need help pls, ty

**Comment by J7mbo** [comment]
You need all four values, as per the twitter documentation. If you don't have it, you need to get it from the twitter site.

**Comment by ThatGamerBlue** [comment]
ok, thanks
