### ISSUE TITLE
Can we get user mail ID using API

### ISSUE THREAD

**Issue by gnanasekaranl** [J7mbo/twitter-api-php#198]
Can we get user e-mail ID using twitter API. If I give user twitter ID ( like @username) using this can I get mail ID of this ID

**Comment by J7mbo** [comment]
A twitter id is a numerical value. The screen name is the @username.

I presume by "mail ID" you mean email address? Is that what you mean?

**Comment by gnanasekaranl** [comment]
Yes, I mean email ID only. Can we get email ID using twitter id or  screen name

**Comment by J7mbo** [comment]
Take a look at [this answer on StackOverflow](http://stackoverflow.com/a/3627563/736809). Basically a user would have to authenticate to provide their email address.

**Comment by J7mbo** [comment]
I'll close the issue, but if there's anything else here feel free to re-open it.
