### ISSUE TITLE
composer.json "error"

### ISSUE THREAD

**Issue by bkdotcom** [J7mbo/twitter-api-php#201]
```
"autoload": {
        "files": ["TwitterAPIExchange.php"]
},
```

should be:
```
"autoload": {
        "classmap": ["TwitterAPIExchange.php"]
},
```

**[Files documentation](https://getcomposer.org/doc/04-schema.md#files)**
> If you want to require certain files explicitly on every request then you can use the 'files' autoloading mechanism. This is useful if your package includes PHP functions that cannot be autoloaded by PHP.

On the other hand classmap:
>You can use the classmap generation support to define autoloading for all libraries that do not follow PSR-0/4. To configure this you specify all directories **or files**(as I've done above) to search for classes.

**TL;DR:**   as currently specified, TwitterAPIExchange.php is being required/included on every page load whether it will be used or not.

**Comment by J7mbo** [comment]
Thanks, committed and it'll go into develop soon.
