### ISSUE TITLE
Time Formatting

### ISSUE THREAD

**Issue by Gooner17** [J7mbo/twitter-api-php#207]
Hi,

Is there a way we can format the date and time created at? If not a date stamp without the time might be useful.

Thanks.

**Comment by J7mbo** [comment]
PHP has plenty of ways to [format DateTime](http://php.net/manual/en/datetime.format.php). Closing as this isn't a question specifically to do with this library and you'll likely get a faster answer that is PHP specific for the data you have on Stackoverflow.
