### ISSUE TITLE
ids":[770558485595557888,770556612692107264]

### ISSUE THREAD

**Issue by hattaabdo** [J7mbo/twitter-api-php#210]
hy
its me again after getting some followers ;),
so i have x2 followers
and i got that error
ids":[770558485595557888,770556612692107264]"
full err:
{"ids":[770558485595557888,770556612692107264],"next_cursor":0,"next_cursor_str":"0","previous_cursor":0,"previous_cursor_str":"0"}
thaknks for help )

**Comment by hattaabdo** [comment]
full page:
<?php ini_set('display_errors', 1);
require_once('TwitterAPIExchange.php');

/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
    'oauth_access_token' => "847143656-kn2GflbzLvfprObqFwwYwXSn7I5vbbzjNY6nI1vT",
    'oauth_access_token_secret' => " ",
    'consumer_key' => "6iBw0t8Fkpf4fTFaSLIMk5Hhg",
    'consumer_secret' => " "
);

/** Perform a GET request and echo the response **/
/** Note: Set the GET field BEFORE calling buildOauth(); **/
$url = 'https://api.twitter.com/1.1/followers/ids.json';
$getfield = '?screen_name=hatta28328506';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);
echo $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();

**Comment by J7mbo** [comment]
You might want to reset your keys and try again then, because in the `TwitterApiExchangeTest.php`, I added a new test (see the commit above) with the following code:

```
$url    = 'https://api.twitter.com/1.1/followers/ids.json';
$method = 'GET';
$params = '?screen_name=hatta28328506';

$data = $this->exchange->request($url, $method, $params);

$this->assertContains('ids', $data);
```

and the result that comes out from the [travis CI build](https://travis-ci.org/J7mbo/twitter-api-php/builds/158403980) running the test is:

```
{
	"ids": [431473085, 766545678793256960, 754330865266728961, 4328223673, 770558485595557888, 770556612692107264],
	"next_cursor": 0,
	"next_cursor_str": "0",
	"previous_cursor": 0,
	"previous_cursor_str": "0"
}
```

**Comment by J7mbo** [comment]
I think the data you get back is correct, the data you provided is exactly what you should expect back as it contains the IDs of the followers that you have.
