### ISSUE TITLE
Long running task looses twitter auth?

### ISSUE THREAD

**Issue by kkretsch** [J7mbo/twitter-api-php#218]
I might have had a problem with a long running php script. It waits on a message queue and gets triggered by external jobs. It creates an twitter object TwitterAPIExchange on start and uses that object for every triggered job. At first this worked. After hours it seems it didn't get any more data from twitter.

I changed the script to create that object per request and will hopefully solved that somehow. But for performance issues I think it would be better to have an object for multiple iterations.

Questions:
- Is there any timeout for the created object? I thought the authentication would be per invocation, like:
$response = $this->twitter->setGetfield($sQuery)->buildOauth($url, 'GET')->performRequest();

- Can I read some status or attribute to see if that object or its connection has been expired?
In this case I can stick to the on object over time but check it and recreate it if needed.

**Comment by J7mbo** [comment]
The current implementation unfortunately requires a new instantiation per request which you found, you can try this by trying to make a new request each time. This'll be fixed soon, sorry about that!

As for connection expiry, this is just a wrapper around a cURL client so if you want to expose the cURL object yourself that may help.
