### ISSUE TITLE
getting ssl cert error

### ISSUE THREAD

**Issue by weswilliams1** [J7mbo/twitter-api-php#220]
I'm getting this error. I'm using PHP 5.6.28 and iis7

Uncaught exception 'Exception' with message 'SSL certificate problem: unable to get local issuer certificate

**Comment by hefengxian** [comment]
please with options
```php
CURLOPT_SSL_VERIFYPEER => false
```

**Comment by J7mbo** [comment]
Closing as this is an old one, if you still have a problem please feel free to re-open and we can work on it.
