### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by iamaamir** [J7mbo/twitter-api-php#222]
following this url https://iag.me/socialmedia/build-your-first-twitter-app-using-php-in-8-easy-steps/
when i am trying to run the app i am getting 500 error on the server although curl is working fine on my server when i test it..

**Comment by EwenH** [comment]
@iamaamir 
   The first thing I would look at is to turn off safe error processing temporarily or to add some error checking. This will hopefully direct you to the line that is causing the issue. Also check to see what your CURLOPT_SSL_VERIFYPEER is set to. Try setting this to false.

**Comment by iamaamir** [comment]
thx i got it ..
