### ISSUE TITLE
Unable to Post

### ISSUE THREAD

**Issue by TopResults** [J7mbo/twitter-api-php#223]
I have been using the same script for the last 4 months; published over 500 tweets within that time and as of December 15th it has stop publishing. The only change I made was I am now **https** from **http** which just happen to occur that day.

I do not see anywhere that would be an issue. I reverted to the basics to grab my tweets and no issues. Unfortunately not posting. Anyone experiencing this?

**Comment by TopResults** [comment]
Further testing. I tried my scripting under another server and it works. 1) Would **https** be blocking it and if so how does one script around it. 2) Can Twitter **Block an IP** and how do find out?

**Comment by EwenH** [comment]
It's hopefully a little easier than Twitter or NSA blocking you. Have a look at your CURL settings and check for CURLOPT_SSL_VERIFYPEER and set this to false.  This is more to do with machine config hopefully

**Comment by EwenH** [comment]
Any update @TopResults ?

**Comment by J7mbo** [comment]
Closing as this is an old one. Any other issues feel free to re-open or create another issue.
