### ISSUE TITLE
Is it possible change the account setting "time_zone"?

### ISSUE THREAD

**Issue by AntonioCortinaL** [J7mbo/twitter-api-php#225]
Hi,

I´m new using twitter api and I follow a tutorial about this class but, when I publish a tweet the "created_at" parameter seems not one that I want (spanish time). I saw a twitter api endpoint  to change account settings (timezone parameter seems the correct to change) in:

https://dev.twitter.com/rest/reference/post/account/settings

Is it possible change it with this library or I can change it by calling this url manually? Because I think this parameter can´t been modify from the twitter app account panel, isn´t?

Can you add a new parameter "settings" for this propose?

Thanks in advance

**Comment by EwenH** [comment]
Hola,
  I've never had an issue with times and I've sent about 0.5m  tweets from an Australian timezone. Can you confirm that your oauthed account is correcrly set for Spanish time?

**Comment by AntonioCortinaL** [comment]
Hi, 

Thanks for the response. How is to set spanish time in my oauthed account ? I have tried set it in my twitter app but I cant, or is in the twitter account settings?

**Comment by EwenH** [comment]
I have two timezones in Ausrltralia to deal with. I set my twitter ac to the correct timezone and I think that all is good when sending via this class. I could be wrong as I always add the local time to the tweet rwxt but I hope I dont think this is a class issue
