### ISSUE TITLE
Fetching posts without count does not work correctly with exclude_replies=true

### ISSUE THREAD

**Issue by phpipam** [J7mbo/twitter-api-php#229]
Hi,

Having issues with fetching last user posts. If `&exclude_replies=true` and `count=x` (for example 5) and within those 5 items is a reply only 4 results are returned. If 2 replies only e are returned etc.

Thanks

**Comment by J7mbo** [comment]
Hi,

I'm not sure this is an issue with this client? If the request is going through successfully to twitter then the problem must be on their end in the data they are returning?

**Comment by J7mbo** [comment]
Closing due to no reply.
