### ISSUE TITLE
Mixed Content warnings in Chrome console

### ISSUE THREAD

**Issue by LondonCityMedia** [J7mbo/twitter-api-php#242]
Hi there,

Thanks for this great library.

I'm sure there's a simple solution to this that I can't find - I'm running your library on a secure site and the profile images that are returned are using the HTTP protocol instead of HTTPS, which is producing Mixed content warnings in Chrome.

Is there a parameter I can pass that asks for the secure paths instead?

Thanks
Sean

**Comment by J7mbo** [comment]
It uses cURL under the hood, and you can pass any extra cURL headers you want int via the `performRequest()` method as a [second parameter](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L274). Does that help?

If profile images are returned directly by the API on twitter's side, I'm not sure there's anything we can do about that.

**Comment by LondonCityMedia** [comment]
@J7mbo Thanks - it does a little. Any idea what header I need to use?

I've currently got:

```
$results = $twitter->setGetfield($getfield)
	             ->buildOauth($url, $requestMethod)
	             ->performRequest();
```

**Comment by J7mbo** [comment]
As this is an old issue, I'm closing it, but if you still feel that something needs to be addressed, please feel free to reopen or open a new issue, I'll put it as a higher priority, and we'll solve it together! :)
