### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ghost** [J7mbo/twitter-api-php#243]
![2017-08-11_110906](https://user-images.githubusercontent.com/11320080/29205742-5498eea8-7e87-11e7-8cf9-777c5b511219.png)
Problems with wamp?

**Comment by Thunder33345** [comment]
i think it's caused because you didnt set up your certs for CURL properly

**Comment by ghost** [comment]
Hi @Thunder33345 !
It works if I add
`CURLOPT_SSL_VERIFYPEER => false` to $options
but I'm not sure if it's called "properly"

**Comment by J7mbo** [comment]
Yep, that's because you need to set up your cURL certificates properly. Google is your friend here :)

**Comment by abrahaobittar** [comment]
Download the cacert.pem from here https://curl.haxx.se/docs/caextract.html and change your php.ini to this: curl.cainfo = "<cacert.pem_path>/cacert.pem";

**Comment by J7mbo** [comment]
Closing this as no response and it doesn't seem directly related to the library but more to PHP instead. If this is not the case, please feel free to re-open / create a new issue.

**Comment by J7mbo** [comment]
PS - happy to accept README PRS highlighting this as an issue for windows users so we can avoid threads like this :)
