### ISSUE TITLE
GET parameters as an array

### ISSUE THREAD

**Issue by ghost** [J7mbo/twitter-api-php#244]
Is it not supported?
For POST we can use an array for parameters. Can we use an array for GET requests too?

**Comment by ghost** [comment]
it seems like with the help of `http_build_query` it works fine...
```
$get_params = [
	"screen_name" => "web2033",
	"exclude_replies" => true,
	"include_rts" => false,
	"count" => 5,
	"trim_user" => 1,
];
$getfield = '?' . http_build_query($get_params, '', '&');
```

**Comment by J7mbo** [comment]
You're totally right, the order of methods and parameters is awful in this 1.0 version. I think for 2.0 we should do this.
