### ISSUE TITLE
[Off topic] Is this library still active?

### ISSUE THREAD

**Issue by ErikThiart** [J7mbo/twitter-api-php#245]
Hello is this still the correct API
I see it is PHP version 5.3.10 which is old.

**Comment by ErikThiart** [comment]
In fact, it does not seem to work anymore.

`          public 'code' => int 32
          public 'message' => string 'Could not authenticate you.'`

**Comment by EwenH** [comment]
Hi @ErikThiart,
   The project is still active and works exceedingly well for the majority of the Twitter API methods (there might be an odd new method not covered) altough I Have yet to use it on PHP 7

**Comment by ErikThiart** [comment]
I am struggling a little bit I tried both php 5.6 and php 7 still get that "could not authenticate you" I have SSL setup in wamp etc.

This is the example I tried:

$url = 'https://api.twitter.com/1.1/search/tweets.json';
$getfield = '?q=#nerd';
$requestMethod = 'GET';

$twitter = new TwitterAPIExchange($settings);
$response = $twitter->setGetfield($getfield)
    ->buildOauth($url, $requestMethod)
    ->performRequest();

var_dump(json_decode($response));

From here: https://github.com/J7mbo/twitter-api-php/wiki/Twitter-API-PHP-Wiki I did this: https://stackoverflow.com/questions/12916539/simplest-php-example-for-retrieving-user-timeline-with-twitter-api-version-1-1/15314662#15314662

**Comment by EwenH** [comment]
Have a look at a number of other closed threads for  CURLOPT_SSL_VERIFYHOST and see if this fixes your issue. Whilst you should verify the host always, you may need to reload your certs file. Alternatively have a look at one of the test scripts which work well under 5.6

**Comment by J7mbo** [comment]
It works and exists because a lot of people require 5.3 support and an extremely simple set of methods :)

**Comment by J7mbo** [comment]
Closing this as no response. If this is not the case and there's still a problem, please feel free to re-open / create a new issue.
