### ISSUE TITLE
New 280 Twitter character limit - Anyone using yet?

### ISSUE THREAD

**Issue by EwenH** [J7mbo/twitter-api-php#252]
Not an issue per-se but having a **brief** read of the API it looks rather complex where you post your tweet of 140 and then add to it but I could be wrong. 

Has anyone played with it yet and can add an example?

**Comment by ghost** [comment]
Seems like it works with new capacity without changing anything

https://twittercommunity.com/t/updating-the-character-limit-and-the-twitter-text-library/96425

> Starting today, you’ll be able to use the standard Twitter API to send these longer updates in those languages, with no code changes required relating to the POST statuses/update endpoint

I've just changed value to reflect a new capability (277 instead of 137):
```
$caption = substr($quote['quote'], 0, 277);
		$caption = trim($caption);
		if ( mb_strlen($quote['quote']) > 277 ){
			$caption .= '...';
		}
```

**Comment by EwenH** [comment]
Thanks @web2033 - I have just tested this on an alert tweet and it works perfectly. As with you, I upped the cutoff and hey presto where I had to send two or more tweets previously, it should fit more often than not into one.
