### ISSUE TITLE
Line breaks in statuses/update.json

### ISSUE THREAD

**Issue by eddieharrison** [J7mbo/twitter-api-php#254]
Hi, I'm trying to post a tweet (via the API and this library) that contains line breaks (\n) and don't seem to be able to, please can anyone help?

I've obviously attempted it without changing anything in the TwitterAPIExchange class and they just land on Twitter as the text "\n".

I then attempted to look into why (in this library code) and found that the status is urlencoded (by rawurlencode in the build oauth sig and http_build_query in the CURLOPT_POSTFIELDS options). This converts the "\n" to "%5Cn" before being sent across to Twitter.

I've attempted to str_replace("%5Cn", '\n', x) this (and also the sig) to send to see if sending Twitter the raw "\n" works but this still doesn't.

Ran out of ideas! Please can anyone help? I've not read anything online re this not being possible by API requests.

Many thanks in advance! Eddie

**Comment by J7mbo** [comment]
Have you tried `\r\n`? I haven't tested this but that's worth a first shot!

**Comment by eddieharrison** [comment]
Hi, yes I've tried that too and it just lands with those characters on Twitter unfortunately!

**Comment by matt-sonata** [comment]
@eddieharrison I had no trouble posting a simple status, might be worth checking the obvious double quotes instead of single? Here's my code in any case.

$settings = array(
hidden
);

$url = 'https://api.twitter.com/1.1/statuses/update.json';
$requestMethod = 'POST';

$postfields = array(
    'status' => "Test Status 2 \r\n Second Line"
);

$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();

**Comment by eddieharrison** [comment]
*facepalm* ... Thanks Matthew, that's all it was!

**Comment by bryanbassett** [comment]
New to this and grateful this answer is still here, why does the single quote versus double quote matter?

**Comment by drewbrew** [comment]
> why does the single quote versus double quote matter

In PHP (and bourne-compatible shells), strings surrounded with single-quotes do not format any escape sequences other than `\'`.

You can test this in an interactive shell:

```php
$ php -a
Interactive shell

php > echo 'test\r\nline';
test\r\nline
php > echo "test\r\nline";
test
line
php >
```
