### ISSUE TITLE
get the full text for the retweets

### ISSUE THREAD

**Issue by SaeedTaghavi** [J7mbo/twitter-api-php#267]
when I use `tweet_mode=extended`, i get the full_text of tweets, but it still don't work for the retweets, I mean even in extended mode i cannot get the full_text of the retweets?

I appreciate your help. 

`$getfield = '?screen_name='.$screen_name."&tweet_mode=extended&count=30";

    $requestMethod = 'GET';

    $twitter = new TwitterAPIExchange($settings);

    //

    $response = $twitter->setGetfield($getfield)

        ->buildOauth($base_url , $requestMethod)

        ->performRequest();

    $tweets = json_decode($response);`

**Comment by J7mbo** [comment]
Hey! Can you define "doesn't work"? I'm trying to figure out if *this is a library issue*, or if this is a general question about how to use the API? If it's the latter, I'd suggest StackOverflow as you'll usually get a much faster answer :)

**Comment by J7mbo** [comment]
As this is an old issue, I'm closing it, but if you still feel that something needs to be addressed, please feel free to reopen or open a new issue and we'll solve it together! :)
