### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function buildOauth() on null

### ISSUE THREAD

**Issue by birdbreath** [J7mbo/twitter-api-php#293]
Returns:

Fatal error: Uncaught Error: Call to a member function buildOauth() on null. .....line 32

Any idea why?

<img width="655" alt="Screen Shot 2020-10-05 at 5 34 01 PM copy" src="https://user-images.githubusercontent.com/72421806/95146622-262ad580-0733-11eb-80f8-8ef341e790fe.png">
idea why?

_Originally posted by @birdbreath in https://github.com/J7mbo/twitter-api-php/issue_comments/703965687_

**Comment by birdbreath** [comment]
added:
echo "$twitter->buildOauth($url, $requestMethod)";

result:
https://upload.twitter.com/1.1/media/upload.json
POST
(https://upload.twitter.com/1.1/media/upload.json, )

**Comment by birdbreath** [comment]
added:
echo "$twitter->buildOauth($url, $method)";

result:
(https://upload.twitter.com/1.1/media/upload.json, POST)

**Comment by J7mbo** [comment]
Hi. I don't think anyone is going to look at the picture of your code and type it out character by character so they can test it.
 
So others can help you better, it might be better to paste the actual code into the box. The [github docs](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) can help you format your code here.

**Comment by J7mbo** [comment]
However, I can see right from the get that you have not initialised the `$twitter` variable to anything when you try and use it for the first time. It doesn't exist yet. You need to create it.

> Call to a member function buildOauth() on null. 

You're trying to call `buildOauth` on null, something that doesn't exist. You want to be calling that on something that does exist.

**Comment by birdbreath** [comment]
Great catch. I totally missed it. It worked perfectly. Thanks

**Comment by birdbreath** [comment]
And in there future I will be including text samples
