### ISSUE TITLE
Can not send  direct message

### ISSUE THREAD

**Issue by ZarchiMohammad** [J7mbo/twitter-api-php#297]
I wrote this code:

![ice_screenshot_20210128-173026](https://user-images.githubusercontent.com/11005782/106148661-905a0100-618e-11eb-9e25-490ab21a7c36.png)

and give this error:
`{"errors":[{"code":32,"message":"Could not authenticate you."}]}`

My permissions: Read, write, and direct messages
Also i have this error on **TwitterAPIExchange** class:
`PHP Warning:  rawurlencode() expects parameter 1 to be string, array given in .../TwitterAPIExchange.php on line 325`

What am i do?

**Comment by Schiocco** [comment]
Same issue (PHP Warning: rawurlencode() expects parameter 1 to be string, array given). It doesn't work for arrays of arrays as post_field (in Postman you need to send the array as plan text(raw) body), if I do the same via this class, the signature broken and the error is {"errors":[{"code":32,"message":"Could not authenticate you."}]}
