### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by mdemo** [J7mbo/twitter-api-php#37]
Would be really helpful if release tags were introduced (+ obviously updating composer.json version accordingly) so that this library can be safely used in production.

**Comment by briedis** [comment]
I vote for this! require dev-master is a pretty bad practice.
I worked around it with a fix version '"j7mbo/twitter-api-php": "dev-master#ab76f1c1e6bf83f0a257216cbaf9932b7cc19a3f"'

..but this does not update correctly..

**Comment by J7mbo** [comment]
v1.0.0 out far too late :-)
