### ISSUE TITLE
empty getfield causes error 32

### ISSUE THREAD

**Issue by simonhaenisch** [J7mbo/twitter-api-php#41]
Hi,

when doing an api get request where no parameters are needed (i.e. geo/id/:place_id), the api responds with error 32 (Could not authenticate you), if you set an empty getfield.

Example:
```php
$url = "https://api.twitter.com/1.1/geo/id/df51dec6f4ee2b2c.json";
$getfield = "";
```

A fast fix would be to set
```php
$getfield = "?foo=bar";
```
the api will just ignore that parameter and the oauth works.

Maybe this is helpful too:
https://dev.twitter.com/discussions/12242

**Comment by J7mbo** [comment]
This should be fixed now.
