### ISSUE TITLE
Critical? Missing rawurlencode

### ISSUE THREAD

**Issue by JohnONeill** [J7mbo/twitter-api-php#46]
From twitter's [API docs on signatures](https://dev.twitter.com/docs/auth/creating-signature,) under "Collecting Parameters":

```
1. Percent encode every key and value that will be signed.
```

As of now, only the key is being encoded when building the base string, as seen [here](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L236). I had to add rawurlencode to the value before it started working.

For those on the same hunt as me, I also found [this](https://dev.twitter.com/discussions/3072) a very useful thread.

**Comment by J7mbo** [comment]
This should now be fixed :+1:
