### ISSUE TITLE
How to upload images with direct url?

### ISSUE THREAD

**Issue by khurshid-alam** [J7mbo/twitter-api-php#50]
Image upload simply fails with direct url as input. It doesn't show any error.

This is what I am trying to do:

```

$image = "http://i.imgur.com/f5v6ath.png"

$url = 'https://api.twitter.com/1.1/statuses/update_with_media.json';
$requestMethod = 'POST';


/** POST fields required by the URL above. See relevant docs as above **/
$postfields = array(
    'status' => "Testing mentions with images",
    'media[]' => "@{$image}"
);


$twitter = new TwitterAPIExchange($settings);
$response = $twitter->buildOauth($url, $requestMethod)
             				  ->setPostfields($postfields)
             				  ->performRequest();
print_r($response);

```

But it does not work. And It does not show any error. 

However it works for local images (`$image = "image-file.png"`).

What am I doing wrong?

**Comment by dibeesh** [comment]
update_with_media is Deprecated

**Comment by J7mbo** [comment]
Update with media is indeed deprecated. You can use `media_upload` which was fixed in 1.0.1.

**Comment by khurshid-alam** [comment]
@J7mbo 

It doesn't work even with https://upload.twitter.com/1.1/media/upload.json url. 

It gives me following error when i try to use direct url:
```json
{"errors":[{"code":38,"message":"media parameter is missing."}]}
```
From api it needs to be either raw binary or base64 encode which should be taken care by this library. Do this library support this? Otherwise I will file a new bug.

**Comment by Amol023** [comment]
https://twittercommunity.com/t/upload-media-from-a-url-third-party-web-storage/94293

I don't think twitter supports that
