### ISSUE TITLE
Could not authenticate you, code 32

### ISSUE THREAD

**Issue by philipjohn** [J7mbo/twitter-api-php#54]
I believe I have a pretty simple usage of this library, but I'm receiving the following response from Twitter:

```
{"errors":[{"message":"Could not authenticate you","code":32}]}
```

Here is my code;

```
require_once 'TwitterAPIExchance.php';
$settings = array(
    'oauth_access_token' => "<snip>",
    'oauth_access_token_secret' => "<snip>",
    'consumer_key' => "<snip>",
    'consumer_secret' => "<snip>"
);
$url = 'https://api.twitter.com/1.1/search/tweets.json';
$requestMethod = 'GET';
$getfields = '?q=foobar&result_type=recent&count=50';
$twitter = new TwitterAPIExchange($settings);

// Get tweets
$data = $twitter->buildOauth($url, $requestMethod)
            ->setGetfield($getfields)
            ->performRequest();

print $data;
```

I started off using an old Twitter app used for something else so I create an entirely new app and switched to those credentials instead. Still no dice. 

I'm working on a dev area so moved the script to the production server to make sure it wasn't that. It wasn't.

Any ideas what, if anything, I'm doing wrong?

**Comment by dixeam** [comment]
I tried it for both but not working.,....

**Comment by ChristopheVilleger** [comment]
Any chance to have a clear answer ?
