### ISSUE TITLE
Bad Creds are Good Creds

### ISSUE THREAD

**Issue by johnstew** [J7mbo/twitter-api-php#61]
I tried using this and was really hoping it would work but of course I ran into a wall. I plugged in my creds from my Twitter Application and I get 
```
'Make sure you are passing in the correct parameters'
```

I have verified that the parameters are correct by testing them on another code snippet I found for the Twitter API and it actually worked fine and I got all of my tweets. I'd like to use yours as it is much cleaner. If you have any information I'd appreciate it. Thanks for the code though.

**Comment by J7mbo** [comment]
Protected tweets are on Twitter's end unfortunately... I can't see a way around this. An old issue but closing as I'm pruning the old issues.
