### ISSUE TITLE
Multiple Feeds on one site(diff' pages). 2 different Twitter accounts

### ISSUE THREAD

**Issue by danny-faith** [J7mbo/twitter-api-php#62]
I have a website that has one successful twitter feed being displayed using twitter-api-php. The website is Wordpress powered and here is the code for the successful Twitter feed. The following file is where I set the Keys and Tokens etc. You'll notice that $twitter_data is where the data is stored. 

/************ This file twitter.php
*************************************************/

    require_once('TwitterAPIExchange.php');

    $settings = array(
        'oauth_access_token' => "123456",
        'oauth_access_token_secret' => "123456",
        'consumer_key' => "123456",
        'consumer_secret' => "123456"
    );

    $url = 'https://api.twitter.com/1.1/statuses/user_timeline.json';
    $getfield = '?screen_name=MyScreenNameOne&count=2';
    $requestMethod = 'GET';

    $twitter = new TwitterAPIExchange($settings);
    $twitter_data = $twitter->setGetfield($getfield)
                 ->buildOauth($url, $requestMethod)
                 ->performRequest(); 

/********* end file

This file is where the tweets are displayed.
/************ This file twitter.php
*************************************************/

    require('library/twitter/twitter.php');

    $twitter_data = json_decode($twitter_data);

    foreach($twitter_data as $key => $value)
    {
        $text = $value->text;

        echo $value->text;
        echo $value->screen_name;
        echo 'whatever I want to display from the tweet';
    }

/********* end file

I then have another Twitter feed that I am trying to display by essentially using the same two files but with slightly changed names (twitter-two.php and sidebar-two.php).

The file sidebar-two.php is almost identical apart from at the top I require require('library/twitter/twitter-two.php');.

My twitter-two.php is also nearly identical apart from different Keys, Tokens and the screen name. I'm going to post the code anyway incase I'm missing something.

/************ This file twitter-two.php
*************************************************/

    require_once('TwitterAPIExchange.php');

    $settings = array(
        'oauth_access_token' => " 123456",
        'oauth_access_token_secret' => "123456",
        'consumer_key' => "123456",
        'consumer_secret' => "123456"
    );

    $url = 'https://api.twitter.com/1.1/statuses/user_timeline.json';
    $getfield = '?screen_name=MyScreenNameTwo&count=2';

    $requestMethod = 'GET';

    $twitter = new TwitterAPIExchange($settings);
    $twitter_data = $twitter->setGetfield($getfield)
                 ->buildOauth($url, $requestMethod)
                 ->performRequest();

For some reason this twitter doesn't come up with anything. I have tried everthing I can think of to debug this. If I put the working Key, Tokens and MyScreenNameOne in twitter-two.php and Tweets came from MyScreenNameOne. I then changed them back and no dice. I spat out the var_dump of $twitter_data and $twitter in file twitter-two.php and got back this (below). 

$twitter
object(TwitterAPIExchange)#586 (8) { ["oauth_access_token":"TwitterAPIExchange":private]=> string(51) " xxxxxx" ["oauth_access_token_secret":"TwitterAPIExchange":private]=> string(45) "xxxxxx" ["consumer_key":"TwitterAPIExchange":private]=> string(22) "xxxxxx" ["consumer_secret":"TwitterAPIExchange":private]=> string(43) "xxxxxx" ["postfields":"TwitterAPIExchange":private]=> NULL ["getfield":"TwitterAPIExchange":private]=> string(30) "?screen_name=MyScreenNameTwo&count=2" ["oauth":protected]=> array(9) { ["oauth_consumer_key"]=> string(22) "xxxxxx" ["oauth_nonce"]=> int(1393256254) ["oauth_signature_method"]=> string(9) "HMAC-SHA1" ["oauth_token"]=> string(51) "xxxxxx" ["oauth_timestamp"]=> int(1393256254) ["oauth_version"]=> string(3) "1.0" ["screen_name"]=> string(9) "MyScreenNameTwo" ["count"]=> string(1) "2" ["oauth_signature"]=> string(28) "xxxxxx =" } ["url"]=> string(55) "https://api.twitter.com/1.1/statuses/user_timeline.json" } 

$twitter_data
object(stdClass)#5936 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#5937 (2) { ["message"]=> string(23) "Bad Authentication data" ["code"]=> int(215) } } }

Does anyone have any idea what could be causing my to receive no tweets?

**Comment by J7mbo** [comment]
Hi, I'm not sure what this is, but it seems to be a problem with your application configuration specifically, not with the library.
