### ISSUE TITLE
POST gives me {"errors":[{"message":"Could not authenticate you","code":32}]}

### ISSUE THREAD

**Issue by rvalsan** [J7mbo/twitter-api-php#64]
Hi,

My GET calls works perfect but I cant seem to post no matter what I tried. I tried single word statuses, urlencoding etc.

GET (Works)

/** URL for REST request, see: https://dev.twitter.com/docs/api/1.1/ **/
$url = 'https://api.twitter.com/1.1/statuses/mentions_timeline.json';
$requestMethod = 'GET';

/** GET fields required by the URL above. See relevant docs as above **/
$getfield = '?count=5';

/** Perform a POST request and echo the response **/
$twitter = new TwitterAPIExchange($settings);
$txtTwitter = $twitter->setGetfield($getfield)->buildOauth($url, $requestMethod)->performRequest();

POST (Not working)

/** URL for REST request, see: https://dev.twitter.com/docs/api/1.1/ **/
$url = 'https://api.twitter.com/1.1/statuses/update.json';
$requestMethod = 'POST';

/** POST fields required by the URL above. See relevant docs as above **/
$postfields = array('status'=> 'test',
'in_reply_to_status_id' => 'rvalsan'
);

/** Perform a POST request and echo the response **/
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
->setPostfields($postfields)
->performRequest();

Both use the same settings
/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
'oauth_access_token' => "token",
'oauth_access_token_secret' => "secret",
'consumer_key' => "key",
'consumer_secret' => "secret"
);

**Comment by lakshmananvelusamy** [comment]
@J7mbo  Hi James, Thanks for the wonderful utility. 

I am using your latest library. The get calls are going fine but the post calls are returning "{"errors":[{"code":32,"message":"Could not authenticate you."}]}". The tokens seem okay and the app has both read & write permissions. Could you please help?

**Comment by J7mbo** [comment]
Hi @lakshmananvelusamy, could you open your own *new* issue and also paste the code in that you are using.

**Comment by lakshmananvelusamy** [comment]
Hi James, Opened https://github.com/J7mbo/twitter-api-php/issues/145.
Thanks!

**Comment by mehulsbhandari** [comment]
{"errors":[{"code":32,"message":"Could not authenticate you."}]}

Please Help !!

**Comment by J7mbo** [comment]
Can you post your code? Cheers.

**Comment by mehulsbhandari** [comment]
Thanks for reply 

require_once('TwitterAPIExchange.php');

$settings = array(
    'oauth_access_token' => "XXXXXXXXXXXX",
    'oauth_access_token_secret' => "YXXXXXXXXXXXXXXX",
    'consumer_key' => "XXXXXXXXXXXXXX",
    'consumer_secret' => "XXXXXXXXXXXXXXXX"
);

$url = 'https://api.twitter.com/1.1/followers/list.json';
$getfield = '?username=mehulsbhandari&skip_status=1';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);
$json = $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();  
print_r(json_decode($json));

**Comment by mehulsbhandari** [comment]
I have also change ... TwitterAPIExchange.php

 $options = array( 
            CURLOPT_HTTPHEADER => $header,
            CURLOPT_HEADER => false,
            CURLOPT_URL => $this->url,
**            CURLOPT_SSL_VERIFYPEER => false,**
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 10,
        );

**Comment by mehulsbhandari** [comment]
@J7mbo 
Please Help

**Comment by mehulsbhandari** [comment]
Done .. Thanks ...
Create New App Done..
:+1:

**Comment by mynote** [comment]
Most common problem is that there is an error in the consumer key or secret if you get the Could not authenticate you.

This usually happens if you copy/paste it from the twitter site. It has a whitespace at the beginning of the customer key which is not visible in all IDEs.

Please revalidate it using notepad or another editor and remove all whitespaces at the end and beginning of your data.

**Comment by SunnyKart** [comment]
Thanks man #mynote u just saved my day

**Comment by Eng-Fouad** [comment]
I was following the [official documentation][1] to construct the signature and I was adding `include_entities` for every request which is wrong. I removed it and then everything works fine.


  [1]: https://dev.twitter.com/oauth/overview/creating-signatures

**Comment by koese66** [comment]
I need help please. I get the same error.
Here ist my code.
`// Upload image to twitter
                    $url = "https://upload.twitter.com/1.1/media/upload.json";
                    $requestMethod = "POST";
                    $media = file_get_contents($temp);
                    $params = array(
                        "media" => $media,
                    );

                    $twitter = new TwitterAPIExchange($settings);


                    $result = $twitter->setPostFields($params)
                        ->buildOauth($url, $requestMethod)
                        ->performRequest();

                    // Result is a json string
                    $result = json_decode($result);

                    $media_ids = $result->media_id_string;

                    // Post on Twitter
                    $url = "https://api.twitter.com/1.1/statuses/update.json";
                    $requestMethod = "POST";
                    $getfield = "?status=$status&media_ids=$media_ids";

                    $twitter = new TwitterAPIExchange($settings);
                    $res = json_decode($twitter->buildOauth($url, $requestMethod)
                        ->setGetField($getfield)
                        ->performRequest());`
