### ISSUE TITLE
Count does not work

### ISSUE THREAD

**Issue by gretarmagg** [J7mbo/twitter-api-php#66]
Hi there.  I'm using this API to fetch the latest tweets with the hashtag mitthverfi on a website.  My website only displays the 4 latest tweets and when I set my getfield to count=10 or some higher number that does not change anything.  When I try count=1 I only get one tweet.

How can I make this display all tweets or maby just more then the latest 4 ?

**Comment by J7mbo** [comment]
Very old post, sorry... but this should be fixed :-)
