### ISSUE TITLE
error 32 if get parameters are not passed

### ISSUE THREAD

**Issue by abhijith-shetty** [J7mbo/twitter-api-php#68]
Hey,

Thanks for the library. 

I was trying to call "https://api.twitter.com/1.1/statuses/home_timeline.json" API using your library and was getting error 32 from twitter.

the code looks like 

$url = 'https://api.twitter.com/1.1/statuses/home_timeline.json';
$getfield = '';
$requestMethod = 'GET';

echo $twitterLib->setGetfield($getfield)
                ->buildOauth($url, $requestMethod)
                ->performRequest();

After some research I found some issues in the TwitterAPIExchange file at line 152. It was just checking for is_null and since I had given this condition ( $getfield = ''; ) it was failing and going inside the loop.

So you can just fix it with  [ if (!is_null($getfield) && trim($getfield)!="") ] so it checks even if the values are empty.

Regards

**Comment by J7mbo** [comment]
The getfield problem is fixed now...
