### ISSUE TITLE
Installs as .git repo

### ISSUE THREAD

**Issue by johnerck** [J7mbo/twitter-api-php#69]
After I run php composer.phar update it installs as a git versioned directory. When I git add . and then do a git commit followed by a push, then, when I'm on another machine and do a git pull the files don't come in and my production app is now broken. Thank you so much for writing this library. Do you know how I would go about resolving my issue? Why does php composer.phar update install a new git repo? I'd like just the files. What are your thoughts? Thank you!!

**Comment by J7mbo** [comment]
Sorry, I can't help you with this specific git issue (I know it's an old issue but I'm closing old issues).
