### ISSUE TITLE
Twitter API error with `users/lookup` endpoint when POST'ing, but not GET'ing.

### ISSUE THREAD

**Issue by meitar** [J7mbo/twitter-api-php#70]
I've been exploring the Twitter API, but when I tried using the 'users/lookup' endpoint, I consistently received "Sorry, that page does not exist" errors.

However, when using [their dev console](https://dev.twitter.com/console), I am able to get the correct result. This test code fails:

```php
$url = 'https://api.twitter.com/1.1/users/lookup.json';
$fields = array('screen_name' => 'lifehacker');
$data = $twitter->buildOauth($url, 'POST')->setPostfields($fields)->performRequest();
```

All POST request seems to work without issue, *except* ones to `users/lookup`. I thought maybe the problem was that cURL was using `multipart/form-data` while the Twitter console was always sending requests as `application/x-www-form-urlencoded`, but I was unable to get anything except the "Sorry, that page does not exist" error code 34 regardless of the POST's request `Content-Type` I sent.

Frustratingly, I can't seem to figure out how to examine the request body using PHP cURL, only its headers.

When I change this to a GET, it works. This test code succeeds:

```php
$url = 'https://api.twitter.com/1.1/users/lookup.json';
$fields = '?screen_name=lifehacker';
$data = $twitter->setGetfield($fields)->buildOauth($url, 'GET')->performRequest();
```

However [Twitter's documentation explicitly mentions a POST is recommended for this endpoint](https://dev.twitter.com/docs/api/1.1/get/users/lookup):

> You are strongly encouraged to use a POST for larger (up to 100 screen names) requests.

So, I feel like this is a bug.

**Comment by J7mbo** [comment]
Looks like this is no longer an issue :+1: Merging in a test to prove this.
