### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by sepehr-y** [J7mbo/twitter-api-php#72]
your composer settings are not right!
after composer update, it won't make a name space for your library in autoload_namespaces.php!

please read this post and make it right :) it'll only take 5 minutes.
https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/

**Comment by J7mbo** [comment]
This doesn't seem to be a large issue - please feel free to submit a PR if anyone believes otherwise. Currently pruning old issues .... :-)
