### ISSUE TITLE
Application-only auth

### ISSUE THREAD

**Issue by OllieTerrance** [J7mbo/twitter-api-php#73]
There are a few API calls that [don't require a logged-in user to access](https://dev.twitter.com/docs/auth/application-only-auth), just an application key/secret.  Are there any plans to implement this here?  At the moment, both application and OAuth keys are required for any request (or `Exception: Make sure you are passing in the correct parameters` if not).

**Comment by J7mbo** [comment]
This app does do OAuth, but I'm not sure exactly what is required here. This is an old issue so unless OP has found a solution / wants to discuss more / switched libs I'm closing.
