### ISSUE TITLE
buildOauth is not necessary

### ISSUE THREAD

**Issue by fulldecent** [J7mbo/twitter-api-php#76]
Is Oauth not required for every request? If this functionality be moved into `performRequest` to reduce verbosity.

````
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();

$twitter = new TwitterAPIExchange($settings);
echo $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();
````

**Comment by J7mbo** [comment]
I agree, there doesn't need to be exclusivity... but the initial design decision involved being able to pass a string for the get field, and an array for the post field. Unfortunately, it sucks, but these now *must* stay for backward compatibility reasons...
