### ISSUE TITLE
Failed to validate signature and token

### ISSUE THREAD

**Issue by authyrtyr** [J7mbo/twitter-api-php#77]
I'm trying to figure out how to get a user's authorization to tweet from their account using the API and my understanding is that you need to use oauth/request_token to get the token from them (although the description of oauth/authorize seems to indicate that it's also used for that and I'm unclear as to how they tie into eachother). However, when I use this library to try and make a request to that REST URL I get back "Failed to validate oauth signature and token". What I've found on the internet suggests that this is due to an incorrect time value or signing method, both of which I believe are handled by the library behind the scenes. Here's the code I'm using, tell me if I've done anything wrong.

<?php

        require_once('twitter-api-php/TwitterAPIExchange.php');

        $settings = array(
            'oauth_access_token' => "[omitted]",
            'oauth_access_token_secret' => "[omitted]",
            'consumer_key' => "[omitted]",
            'consumer_secret' => "[omitted]"
        );

        $url = 'https://api.twitter.com/oauth/request_token';
        $requestMethod = 'POST';
        $postfields = array(
                'oauth_callback' => 'https:/mysite.com/finish.html',
        );

        $twitter = new TwitterAPIExchange($settings);
        echo $twitter->buildOauth($url, $requestMethod)->setPostfields($postfields)->performRequest();

 ?>

**Comment by alexharveyeu** [comment]
I believe this needs to be a header:
  oauth_callback' => 'https:/mysite.com/finish.html'

**Comment by J7mbo** [comment]
Can you confirm that this is still an issue?

**Comment by J7mbo** [comment]
I'm closing as no response from OP, but if anyone still has an issue with this problem feel free to comment and we'll work on it together.
