### ISSUE TITLE
POST DM Destroy creates "Error code":38,"message":"ID parameter is missing."

### ISSUE THREAD

**Issue by 1John1** [J7mbo/twitter-api-php#78]
Hi J7mbo,

I'm having some problems when I POST a command to delete a Direct Message. Each time it's like the ID value isn't being sent. This used to work no problem then stopped working some time ago, I've just started playing with it again.

       $dmid = "485592984080363520";

	$url = "https://api.twitter.com/1.1/direct_messages/destroy.json";
	$requestMethod = 'POST';

	$postfields = array('id' => $dmid);

	$twitter  = new TwitterAPIExchange( $settings );
	echo $twitter->buildOauth($url, $requestMethod )
		     ->setPostfields( $postfields )
		     ->performRequest(); 

This will create the following response:
{"errors":[{"code":38,"message":"ID parameter is missing."}]}

When I use POST to unfavourite a Tweet sending only the 'id' parameter it will work, it seems just the DM Destroy is not working.

I have checked privileges and regenerated API keys and tokens to see if there was an issue with permissions to no avail.

**Comment by J7mbo** [comment]
Although this is a *very* old issue - did twitter end up fixing this? Or is the issue still there?

**Comment by iagdotme** [comment]
@J7mbo unfortunately it still is an issue. Strangely, I can delete dms using a different Twitter library, but not with this one. I did reach out to someone at Twitter (in the API team) and they confirmed the issue, but they never got back to me. So, I don't know if this is a Twitter API issue or an issue with the wrapper. Any thoughts?

**Comment by glenscott** [comment]
@iagdotme would you be able to test with the latest (1.0.1) version of the wrapper and confirm whether it's still an issue?

**Comment by J7mbo** [comment]
I believe this is fixed (and proven to be so) with [testStatusesDestroy()](https://github.com/J7mbo/twitter-api-php/blob/master/test/TwitterAPIExchangeTest.php#L231-L256). 

Try a `composer update` guys to get the latest version and then try again - deletion should work as expected. I'm going to close this issue but if anyone still have a problem they can feel free to continue commenting or create a new, more up-to-date issue.

**Comment by iagdotme** [comment]
@glenscott and @J7mbo - thanks guys! I can confirm that this is now working perfectly. Could you explain what the issue was and what you did to fix it? Just interested!

**Comment by J7mbo** [comment]
@iagdotme It was all to do with encoding of the parameters, I think things were being double encoded somewhere. This would throw off the OAuth signature and so Twitter would reject it. Anyway, a wild @glenscott appeared and fixed all the things so this lib, along with the new tests I wrote that prove endpoints are working and are run on every push / pr thanks to Travis CI, we have a more consistent experience across endpoints. TLDR, it actually works now :+1:

**Comment by iagdotme** [comment]
Thanks, @J7mbo - good to know. Thanks again for producing such an amazing library. You won't believe how many people find it so useful!
