### ISSUE TITLE
Compressed API Response! (deflate, gzip)

### ISSUE THREAD

**Issue by futureweb** [J7mbo/twitter-api-php#84]
Hey there,
this API Integration should use Content Compression for the API Response (https://blog.twitter.com/2012/announcing-gzip-compression-streaming-apis)
Reduced Page-Generation-Time (with deactivated Memcache Result Cache) from 7 Seconds to 1,5 Seconds ... ;-)

It's simple to hack into ... just add this Line to the CURL Options (Line 199):
          CURLOPT_ENCODING => '',

Whole Options:
        $options = array( 
            CURLOPT_HTTPHEADER => $header,
            CURLOPT_HEADER => false,
            CURLOPT_URL => $this->url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_ENCODING => '',
        );

Have fun
Andreas Schnederle-Wagner

**Comment by J7mbo** [comment]
This would work if #94 was updated, then additional cURL options could be added as the user requires.

**Comment by J7mbo** [comment]
I'm going to close this for the moment - if anyone would like to pick this up in the future please feel free to comment.
