### ISSUE TITLE
Could not authenticate you in Could not authenticate you

### ISSUE THREAD

**Issue by gaurav10times** [J7mbo/twitter-api-php#85]
from last 6 month i am using this library fro fetching tweets from twitter api, but suddenly i am getting 

array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(2) {
      ["message"]=>
      string(26) "Could not authenticate you"
      ["code"]=>
      int(32)
    }
  }
}

My code is
=============================
$settings = array(
                   'oauth_access_token' => "XXXXX",
                   'oauth_access_token_secret' => "XXXXX",
                   'consumer_key' => XXXXXXXXXXXXX",
                   'consumer_secret' => "XXXXXXXXXXXXX"
           );
          $url = 'https://api.twitter.com/1.1/search/tweets.json';
        $requestMethod = 'GET';
        if(isset($next))
        {
        $getfield = $next.'&since_id='.$since_id;
       
        }
        else 
         $getfield = '?q='.$hashtag.'&result_type=recent&since_id='.$since_id;
        
       
//echo $keyword;
//echo $getfield;
//echo "<br>";
// Perform the request
$twitter = new TwitterAPIExchange($settings);
$string = json_decode($twitter->setGetfield($getfield)
->buildOauth($url, $requestMethod)
->performRequest(),$assoc = TRUE);

 var_dump($string);
 output of this request is 
array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(2) {
      ["message"]=>
      string(26) "Could not authenticate you"
      ["code"]=>
      int(32)
    }
  }
}

**Comment by J7mbo** [comment]
Closing due to lack of updates from OP.
