### ISSUE TITLE
Not getting cursors with "retweeters/ids"

### ISSUE THREAD

**Issue by richicru** [J7mbo/twitter-api-php#86]
I'm trying to get de IDs of the retweeters from a "tweet with more than 100 retweets". I always get the cursors=0 with all tweets (over 100RT).
$idd  = 523847332819767296;
$url = "https://api.twitter.com/1.1/statuses/retweeters/ids.json";
$requestMethod = "GET";
$getfield = "?id=$idd";
$twitter = new TwitterAPIExchange($settings);
$string = json_decode($twitter->setGetfield($getfield)
->buildOauth($url, $requestMethod)
->performRequest(),$assoc = TRUE);
print_r($string);

REPONSE:
...2760340740 [96] => 560471456 [97] => 2611583155 [98] => 352507192 [99] => 2237972138 ) [next_cursor] => 0 [next_cursor_str] => 0 [previous_cursor] => 0 [previous_cursor_str] => 0 )

**Comment by kikuso** [comment]
Hi!

I think you will probably have your answer by now, but in case someone else get here looking for a solution to this problem, let me paste what is said in other places about this:

"While this collection supports cursoring, the maximum number of results you can get back from the method is the 100 most recent users who retweeted the tweet. You can use lower count values and cursor through that 100 in multiple pages or you can just use a single request and get that 100, but you can't move beyond the boundaries of that 100."

So, it seems twitter does not want to offer us the capability to work out the actual reach of a particular tweet :(

**Comment by J7mbo** [comment]
Seems like this is a twitter issue, sorry guys :(
