### ISSUE TITLE
Android Error response on Twitter compose new DirectMessage

### ISSUE THREAD

**Issue by praveen2gemini** [J7mbo/twitter-api-php#87]
URL: https://api.twitter.com/1.1/direct_messages/new.json

METHOD:  POST

HEARDER:
Authorization :  OAuth oauth_consumer_key="**********MyConsumerkey*********", oauth_nonce="b7eee73c056c8325f92b7f4317eaa881", oauth_signature="4txB4an%2Ft%2BQsQ%2FUZNeXoT0cnnhs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1415954164", oauth_token="**********MyAccessToken**********, oauth_version="1.0"

KEYPAIR:
user_id = 94311220
screen_name = praveengemini
text = Test Message

{
    "errors": [
        {
            "message": "Could not authenticate you",
            "code": 32
        }
    ]
}

Please help me identify the mistake.
Thank you.

**Comment by J7mbo** [comment]
Sorry, without any code examples or anything, I can't help you with this.
