### ISSUE TITLE
typo in the examples

### ISSUE THREAD

**Issue by nekromoff** [J7mbo/twitter-api-php#90]
https://github.com/J7mbo/twitter-api-php/wiki/Twitter-API-PHP-Wiki

geocode search should be:
$getfield = '?q=&geocode=17.117232,48.148154,20km&count=100';

instead of:
$getfield = '?q=&geocode=17.117232,48.148154,20km&count=100;"';

**Comment by J7mbo** [comment]
Thanks, nice spot! The wiki is open to collaboration from the public so you can feel free to add / modify things in the future if you like. :+1:
