### ISSUE TITLE
uploading media

### ISSUE THREAD

**Issue by miloman** [J7mbo/twitter-api-php#91]
Hi there

It seems that this wrapper does not support upload images to https://upload.twitter.com/1.1/media/upload.json

I think the problem is that the correct headers are not being set, i.e.: i think some of the following needs to be included

Content-Type: multipart/form-data; boundary=

I am trying to have a crack at this but any help would be greatly appreciated.

Thanks

**Comment by kabir-baidhya** [comment]
Yes, I'm too facing this problem. 
Uploading media with url https://upload.twitter.com/1.1/media/upload.json is not supported.

**Comment by miloman** [comment]
I switched to using  https://github.com/jublonet/codebird-php <https://github.com/jublonet/codebird-php>

much better

**Comment by J7mbo** [comment]
There is an issue with the multi-part from that needs to be sorted for media upload.

**Comment by gitboss** [comment]
@J7mbo Thanks for the simple wrapper. Will this issue be fixed anytime soon?

**Comment by luckyshot** [comment]
:+1:  media uploads would be really appreciated! 
Is there any workaround/hack to fix the multi-part form issue?

**Comment by ashleydw** [comment]
+1 any solutions?

**Comment by J7mbo** [comment]
@ashleydw I'm taking a look at this now.. your multipart/form-data addition doesn't seem to work for me, does it for you? Is there anything else you changed to get it working?

**Comment by ashleydw** [comment]
@J7mbo no sorry although the heads get sent i eventually switched. see https://github.com/J7mbo/twitter-api-php/issues/99#issuecomment-95304600

**Comment by J7mbo** [comment]
This is fixed in the latest commit.
