### ISSUE TITLE
Something has changed...

### ISSUE THREAD

**Issue by bbredewold** [J7mbo/twitter-api-php#96]
Since a few weeks my Twitterfeed suddenly stopped working. I don't get any results back...
I use TwitterAPIExchange.php...

{"statuses":[],"search_metadata":{"completed_in":0.01,"max_id":553333061392564225,"max_id_str":"553333061392564225","query":"%23itph","refresh_url":"?since_id=553333061392564225&q=%23itph&include_entities=1","count":20,"since_id":0,"since_id_str":"0"}}

and

{"errors":[{"message":"Sorry, that page does not exist","code":34}]}

Any ideas?

**Comment by mutindaz** [comment]
I am experiencing the same problem. can't search for tweets..

**Comment by ariel17** [comment]
I have experienced the same behaviour with GET users/show resource :( Too bad... This implementation is very nice.

**Comment by jakewhiteley** [comment]
I have been getting this a lot recently with a  lot of my cURL based PHP scripts. The more recent versions of cURL have changed the way they handle SSL certificates from what I can tell. 

A quick fix is that we don't actually need cURL to verify the certificate that Twitter uses.

Just edit the `$options` array in `performRequest()` like so:
``` php
$options = array( 
            CURLOPT_HTTPHEADER => $header,
            CURLOPT_HEADER => false,
            CURLOPT_URL => $this->url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => false // indicates to cURL not to search for the current certificate details
        );
```

And It works again!

**Comment by gridlok** [comment]
Adding that curl parameter worked for me. Thanks jake!
