### ISSUE TITLE
response is empty

### ISSUE THREAD

**Issue by farhantahseen** [J7mbo/twitter-api-php#97]
Everything is going fine but I am getting nothing here its null/false  var_dump($tweets);

$url = 'https://api.twitter.com/1.1/search/tweets.json?';
$getfield = 'q=army';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);

$twitterjson =  $twitter->setGetfield($getfield)
                              ->buildOauth($url, $requestMethod)
                              ->performRequest();
            $tweets = json_decode($twitterjson, true);
            var_dump($tweets);

Everything is going good but $tweets is empty/false

**Comment by J7mbo** [comment]
Try `$getfield = '?q=army';`

**Comment by farhantahseen** [comment]
tried this also. but same result. is there anything else I am missing. I have test var_dump($twitterjson = $twitter->setGetfield($getfield)) this is also good
I have test this in twitter API console there I am getting results

**Comment by J7mbo** [comment]
Before you do that, can you also try: `?q=#army`

**Comment by farhantahseen** [comment]
Ok, I will try this and let you know about this..Thanks for your kind help

**Comment by geiszla** [comment]
I have the same problem I checked the keys and tokens like 3 times, and tried 2 examples (including the above mentioned "q=army"), but var_dump() always returns NULL... What else could I possibly do wrong?

**Comment by J7mbo** [comment]
@geiszla Have you tried **?q=army**. You seem to be missing the `?`.

**Comment by geiszla** [comment]
@J7mbo in the example above, the "?" is at the end of the url string, that's why I wrote that. But I tried it both ways, and it still gives me NULL. Meanwhile I figured out, that the empty json is because of the timeout of the request. But I don't know why this happens. It should at least give an error message..

**Comment by Amekmani** [comment]
I got that issue while building on my local machine, when I moved it to a testing server online it worked just fine. Where are you currently testing from?

**Comment by geiszla** [comment]
I have a free site on 000webhost: http://anondb.webuda.com/refresh.php,
so it should work. Maybe there is something that should be set up on 000webhost?

**Comment by Amekmani** [comment]
I got this error ``` "error:couldn't connect to hostNULL" ```, I'll send you my working code tomorrow when I get back to my desk if you haven't resolved the issue by then.

**Comment by geiszla** [comment]
I found an issue related to my problem: https://github.com/iips-dc/SunriseBaithakApp/issues/8
But it says "cURL is installed by default here. However CurlSSL is only available
with premium accounts.". Is this using curlSSL? And if yes, how can I avoid it?

**Comment by nhawa** [comment]
i have some problem.

**Comment by J7mbo** [comment]
It seems this is an environmental issue? It *must* be something to do with PHP versions or cURL.
