### ISSUE TITLE
Cross-origin image load denied by Cross-Origin Resource Sharing policy.

### ISSUE THREAD

**Issue by 5argon** [J7mbo/twitter-api-php#98]
I sent my request to this
https://api.twitter.com/1.1/users/show.json

And it returned the json just fine. But however when I went to extract user image profile from that json data and assign it to Image.src I immediately get this error.

Originally I knew that requesting things from client side will get cross-domain problem so I moved to php which is server-side. Why the same error again?

**Comment by J7mbo** [comment]
@5argon Did you get any further with this? Could you elaborate?
